export const binData = [
  {
    bin: 0,
    bins: [
      { bin: 0, count: 48 },
      { bin: 1, count: 29 },
      { bin: 2, count: 74 },
      { bin: 3, count: 86 },
      { bin: 4, count: 35 },
      { bin: 5, count: 96 },
      { bin: 6, count: 55 },
    ],
  },
  {
    bin: 1,
    bins: [
      { bin: 0, count: 0 },
      { bin: 1, count: 33 },
      { bin: 2, count: 97 },
      { bin: 3, count: 24 },
      { bin: 4, count: 42 },
      { bin: 5, count: 55 },
      { bin: 6, count: 55 },
    ],
  },
  {
    bin: 2,
    bins: [
      { bin: 0, count: 53 },
      { bin: 1, count: 79 },
      { bin: 2, count: 18 },
      { bin: 3, count: 11 },
      { bin: 4, count: 16 },
      { bin: 5, count: 57 },
      { bin: 6, count: 4 },
    ],
  },
  {
    bin: 3,
    bins: [
      { bin: 0, count: 42 },
      { bin: 1, count: 28 },
      { bin: 2, count: 63 },
      { bin: 3, count: 90 },
      { bin: 4, count: 39 },
      { bin: 5, count: 21 },
      { bin: 6, count: 74 },
    ],
  },
  {
    bin: 4,
    bins: [
      { bin: 0, count: 1 },
      { bin: 1, count: 96 },
      { bin: 2, count: 22 },
      { bin: 3, count: 5 },
      { bin: 4, count: 83 },
      { bin: 5, count: 88 },
      { bin: 6, count: 29 },
    ],
  },
  {
    bin: 5,
    bins: [
      { bin: 0, count: 86 },
      { bin: 1, count: 87 },
      { bin: 2, count: 44 },
      { bin: 3, count: 14 },
      { bin: 4, count: 44 },
      { bin: 5, count: 5 },
      { bin: 6, count: 25 },
    ],
  },
  {
    bin: 6,
    bins: [
      { bin: 0, count: 76 },
      { bin: 1, count: 74 },
      { bin: 2, count: 19 },
      { bin: 3, count: 81 },
      { bin: 4, count: 44 },
      { bin: 5, count: 13 },
      { bin: 6, count: 39 },
    ],
  },
  {
    bin: 7,
    bins: [
      { bin: 0, count: 48 },
      { bin: 1, count: 99 },
      { bin: 2, count: 53 },
      { bin: 3, count: 41 },
      { bin: 4, count: 89 },
      { bin: 5, count: 56 },
      { bin: 6, count: 67 },
    ],
  },
  {
    bin: 8,
    bins: [
      { bin: 0, count: 36 },
      { bin: 1, count: 16 },
      { bin: 2, count: 30 },
      { bin: 3, count: 22 },
      { bin: 4, count: 33 },
      { bin: 5, count: 25 },
      { bin: 6, count: 79 },
    ],
  },
  {
    bin: 9,
    bins: [
      { bin: 0, count: 8 },
      { bin: 1, count: 76 },
      { bin: 2, count: 40 },
      { bin: 3, count: 7 },
      { bin: 4, count: 16 },
      { bin: 5, count: 51 },
      { bin: 6, count: 58 },
    ],
  },
  {
    bin: 10,
    bins: [
      { bin: 0, count: 38 },
      { bin: 1, count: 22 },
      { bin: 2, count: 24 },
      { bin: 3, count: 19 },
      { bin: 4, count: 34 },
      { bin: 5, count: 76 },
      { bin: 6, count: 35 },
    ],
  },
  {
    bin: 11,
    bins: [
      { bin: 0, count: 63 },
      { bin: 1, count: 94 },
      { bin: 2, count: 15 },
      { bin: 3, count: 56 },
      { bin: 4, count: 40 },
      { bin: 5, count: 57 },
      { bin: 6, count: 12 },
    ],
  },
  {
    bin: 12,
    bins: [
      { bin: 0, count: 10 },
      { bin: 1, count: 77 },
      { bin: 2, count: 16 },
      { bin: 3, count: 66 },
      { bin: 4, count: 76 },
      { bin: 5, count: 36 },
      { bin: 6, count: 82 },
    ],
  },
  {
    bin: 13,
    bins: [
      { bin: 0, count: 81 },
      { bin: 1, count: 62 },
      { bin: 2, count: 3 },
      { bin: 3, count: 88 },
      { bin: 4, count: 78 },
      { bin: 5, count: 1 },
      { bin: 6, count: 96 },
    ],
  },
  {
    bin: 14,
    bins: [
      { bin: 0, count: 14 },
      { bin: 1, count: 66 },
      { bin: 2, count: 97 },
      { bin: 3, count: 78 },
      { bin: 4, count: 45 },
      { bin: 5, count: 36 },
      { bin: 6, count: 45 },
    ],
  },
  {
    bin: 15,
    bins: [
      { bin: 0, count: 29 },
      { bin: 1, count: 38 },
      { bin: 2, count: 69 },
      { bin: 3, count: 83 },
      { bin: 4, count: 90 },
      { bin: 5, count: 33 },
      { bin: 6, count: 75 },
    ],
  },
  {
    bin: 16,
    bins: [
      { bin: 0, count: 67 },
      { bin: 1, count: 92 },
      { bin: 2, count: 26 },
      { bin: 3, count: 97 },
      { bin: 4, count: 65 },
      { bin: 5, count: 54 },
      { bin: 6, count: 15 },
    ],
  },
  {
    bin: 17,
    bins: [
      { bin: 0, count: 50 },
      { bin: 1, count: 12 },
      { bin: 2, count: 69 },
      { bin: 3, count: 72 },
      { bin: 4, count: 71 },
      { bin: 5, count: 76 },
      { bin: 6, count: 52 },
    ],
  },
  {
    bin: 18,
    bins: [
      { bin: 0, count: 96 },
      { bin: 1, count: 17 },
      { bin: 2, count: 29 },
      { bin: 3, count: 4 },
      { bin: 4, count: 65 },
      { bin: 5, count: 25 },
      { bin: 6, count: 15 },
    ],
  },
  {
    bin: 19,
    bins: [
      { bin: 0, count: 13 },
      { bin: 1, count: 82 },
      { bin: 2, count: 16 },
      { bin: 3, count: 67 },
      { bin: 4, count: 97 },
      { bin: 5, count: 87 },
      { bin: 6, count: 23 },
    ],
  },
  {
    bin: 20,
    bins: [
      { bin: 0, count: 13 },
      { bin: 1, count: 65 },
      { bin: 2, count: 76 },
      { bin: 3, count: 60 },
      { bin: 4, count: 62 },
      { bin: 5, count: 50 },
      { bin: 6, count: 50 },
    ],
  },
  {
    bin: 21,
    bins: [
      { bin: 0, count: 75 },
      { bin: 1, count: 82 },
      { bin: 2, count: 35 },
      { bin: 3, count: 95 },
      { bin: 4, count: 37 },
      { bin: 5, count: 92 },
      { bin: 6, count: 76 },
    ],
  },
  {
    bin: 22,
    bins: [
      { bin: 0, count: 53 },
      { bin: 1, count: 66 },
      { bin: 2, count: 37 },
      { bin: 3, count: 5 },
      { bin: 4, count: 32 },
      { bin: 5, count: 7 },
      { bin: 6, count: 23 },
    ],
  },
  {
    bin: 23,
    bins: [
      { bin: 0, count: 54 },
      { bin: 1, count: 83 },
      { bin: 2, count: 85 },
      { bin: 3, count: 13 },
      { bin: 4, count: 30 },
      { bin: 5, count: 32 },
      { bin: 6, count: 18 },
    ],
  },
  {
    bin: 24,
    bins: [
      { bin: 0, count: 37 },
      { bin: 1, count: 52 },
      { bin: 2, count: 37 },
      { bin: 3, count: 62 },
      { bin: 4, count: 47 },
      { bin: 5, count: 6 },
      { bin: 6, count: 17 },
    ],
  },
  {
    bin: 25,
    bins: [
      { bin: 0, count: 16 },
      { bin: 1, count: 30 },
      { bin: 2, count: 97 },
      { bin: 3, count: 80 },
      { bin: 4, count: 12 },
      { bin: 5, count: 54 },
      { bin: 6, count: 95 },
    ],
  },
  {
    bin: 26,
    bins: [
      { bin: 0, count: 29 },
      { bin: 1, count: 71 },
      { bin: 2, count: 7 },
      { bin: 3, count: 6 },
      { bin: 4, count: 34 },
      { bin: 5, count: 90 },
      { bin: 6, count: 77 },
    ],
  },
  {
    bin: 27,
    bins: [
      { bin: 0, count: 13 },
      { bin: 1, count: 9 },
      { bin: 2, count: 4 },
      { bin: 3, count: 45 },
      { bin: 4, count: 74 },
      { bin: 5, count: 99 },
      { bin: 6, count: 39 },
    ],
  },
  {
    bin: 28,
    bins: [
      { bin: 0, count: 23 },
      { bin: 1, count: 66 },
      { bin: 2, count: 10 },
      { bin: 3, count: 23 },
      { bin: 4, count: 43 },
      { bin: 5, count: 13 },
      { bin: 6, count: 1 },
    ],
  },
  {
    bin: 29,
    bins: [
      { bin: 0, count: 60 },
      { bin: 1, count: 77 },
      { bin: 2, count: 44 },
      { bin: 3, count: 37 },
      { bin: 4, count: 60 },
      { bin: 5, count: 54 },
      { bin: 6, count: 54 },
    ],
  },
  {
    bin: 30,
    bins: [
      { bin: 0, count: 76 },
      { bin: 1, count: 78 },
      { bin: 2, count: 98 },
      { bin: 3, count: 77 },
      { bin: 4, count: 21 },
      { bin: 5, count: 22 },
      { bin: 6, count: 98 },
    ],
  },
  {
    bin: 31,
    bins: [
      { bin: 0, count: 98 },
      { bin: 1, count: 84 },
      { bin: 2, count: 17 },
      { bin: 3, count: 96 },
      { bin: 4, count: 40 },
      { bin: 5, count: 21 },
      { bin: 6, count: 43 },
    ],
  },
  {
    bin: 32,
    bins: [
      { bin: 0, count: 50 },
      { bin: 1, count: 31 },
      { bin: 2, count: 52 },
      { bin: 3, count: 82 },
      { bin: 4, count: 94 },
      { bin: 5, count: 18 },
      { bin: 6, count: 62 },
    ],
  },
  {
    bin: 33,
    bins: [
      { bin: 0, count: 42 },
      { bin: 1, count: 22 },
      { bin: 2, count: 89 },
      { bin: 3, count: 52 },
      { bin: 4, count: 45 },
      { bin: 5, count: 63 },
      { bin: 6, count: 26 },
    ],
  },
  {
    bin: 34,
    bins: [
      { bin: 0, count: 97 },
      { bin: 1, count: 92 },
      { bin: 2, count: 13 },
      { bin: 3, count: 83 },
      { bin: 4, count: 6 },
      { bin: 5, count: 44 },
      { bin: 6, count: 48 },
    ],
  },
  {
    bin: 35,
    bins: [
      { bin: 0, count: 87 },
      { bin: 1, count: 12 },
      { bin: 2, count: 89 },
      { bin: 3, count: 46 },
      { bin: 4, count: 78 },
      { bin: 5, count: 28 },
      { bin: 6, count: 76 },
    ],
  },
  {
    bin: 36,
    bins: [
      { bin: 0, count: 67 },
      { bin: 1, count: 63 },
      { bin: 2, count: 49 },
      { bin: 3, count: 33 },
      { bin: 4, count: 89 },
      { bin: 5, count: 30 },
      { bin: 6, count: 88 },
    ],
  },
  {
    bin: 37,
    bins: [
      { bin: 0, count: 10 },
      { bin: 1, count: 97 },
      { bin: 2, count: 49 },
      { bin: 3, count: 68 },
      { bin: 4, count: 9 },
      { bin: 5, count: 55 },
      { bin: 6, count: 76 },
    ],
  },
  {
    bin: 38,
    bins: [
      { bin: 0, count: 19 },
      { bin: 1, count: 94 },
      { bin: 2, count: 38 },
      { bin: 3, count: 10 },
      { bin: 4, count: 41 },
      { bin: 5, count: 83 },
      { bin: 6, count: 79 },
    ],
  },
  {
    bin: 39,
    bins: [
      { bin: 0, count: 85 },
      { bin: 1, count: 45 },
      { bin: 2, count: 80 },
      { bin: 3, count: 61 },
      { bin: 4, count: 92 },
      { bin: 5, count: 72 },
      { bin: 6, count: 95 },
    ],
  },
  {
    bin: 40,
    bins: [
      { bin: 0, count: 80 },
      { bin: 1, count: 64 },
      { bin: 2, count: 49 },
      { bin: 3, count: 45 },
      { bin: 4, count: 31 },
      { bin: 5, count: 74 },
      { bin: 6, count: 51 },
    ],
  },
  {
    bin: 41,
    bins: [
      { bin: 0, count: 61 },
      { bin: 1, count: 9 },
      { bin: 2, count: 16 },
      { bin: 3, count: 60 },
      { bin: 4, count: 20 },
      { bin: 5, count: 23 },
      { bin: 6, count: 84 },
    ],
  },
  {
    bin: 42,
    bins: [
      { bin: 0, count: 42 },
      { bin: 1, count: 87 },
      { bin: 2, count: 69 },
      { bin: 3, count: 59 },
      { bin: 4, count: 89 },
      { bin: 5, count: 37 },
      { bin: 6, count: 4 },
    ],
  },
  {
    bin: 43,
    bins: [
      { bin: 0, count: 71 },
      { bin: 1, count: 97 },
      { bin: 2, count: 85 },
      { bin: 3, count: 21 },
      { bin: 4, count: 99 },
      { bin: 5, count: 77 },
      { bin: 6, count: 62 },
    ],
  },
  {
    bin: 44,
    bins: [
      { bin: 0, count: 12 },
      { bin: 1, count: 28 },
      { bin: 2, count: 6 },
      { bin: 3, count: 89 },
      { bin: 4, count: 74 },
      { bin: 5, count: 62 },
      { bin: 6, count: 89 },
    ],
  },
  {
    bin: 45,
    bins: [
      { bin: 0, count: 53 },
      { bin: 1, count: 2 },
      { bin: 2, count: 79 },
      { bin: 3, count: 73 },
      { bin: 4, count: 90 },
      { bin: 5, count: 50 },
      { bin: 6, count: 75 },
    ],
  },
  {
    bin: 46,
    bins: [
      { bin: 0, count: 32 },
      { bin: 1, count: 14 },
      { bin: 2, count: 83 },
      { bin: 3, count: 16 },
      { bin: 4, count: 30 },
      { bin: 5, count: 65 },
      { bin: 6, count: 34 },
    ],
  },
  {
    bin: 47,
    bins: [
      { bin: 0, count: 15 },
      { bin: 1, count: 8 },
      { bin: 2, count: 54 },
      { bin: 3, count: 34 },
      { bin: 4, count: 96 },
      { bin: 5, count: 76 },
      { bin: 6, count: 23 },
    ],
  },
  {
    bin: 48,
    bins: [
      { bin: 0, count: 5 },
      { bin: 1, count: 5 },
      { bin: 2, count: 91 },
      { bin: 3, count: 64 },
      { bin: 4, count: 99 },
      { bin: 5, count: 91 },
      { bin: 6, count: 51 },
    ],
  },
  {
    bin: 49,
    bins: [
      { bin: 0, count: 50 },
      { bin: 1, count: 49 },
      { bin: 2, count: 64 },
      { bin: 3, count: 46 },
      { bin: 4, count: 84 },
      { bin: 5, count: 61 },
      { bin: 6, count: 96 },
    ],
  },
  {
    bin: 50,
    bins: [
      { bin: 0, count: 40 },
      { bin: 1, count: 60 },
      { bin: 2, count: 50 },
      { bin: 3, count: 28 },
      { bin: 4, count: 73 },
      { bin: 5, count: 90 },
      { bin: 6, count: 9 },
    ],
  },
  {
    bin: 51,
    bins: [
      { bin: 0, count: 98 },
      { bin: 1, count: 9 },
      { bin: 2, count: 57 },
      { bin: 3, count: 67 },
      { bin: 4, count: 8 },
      { bin: 5, count: 78 },
      { bin: 6, count: 79 },
    ],
  },
  {
    bin: 52,
    bins: [
      { bin: 0, count: 71 },
      { bin: 1, count: 87 },
      { bin: 2, count: 69 },
      { bin: 3, count: 2 },
      { bin: 4, count: 89 },
      { bin: 5, count: 18 },
      { bin: 6, count: 86 },
    ],
  },
];

export const barData = [
  { letter: 'A', frequency: 816 },
  { letter: 'B', frequency: 149 },
  { letter: 'C', frequency: 278 },
  { letter: 'D', frequency: 425 },
  { letter: 'E', frequency: 1270 },
  { letter: 'F', frequency: 228 },
  { letter: 'G', frequency: 201 },
  { letter: 'H', frequency: 609 },
  { letter: 'I', frequency: 696 },
  { letter: 'J', frequency: 15 },
  { letter: 'K', frequency: 77 },
  { letter: 'L', frequency: 402 },
  { letter: 'M', frequency: 240 },
  { letter: 'N', frequency: 674 },
  { letter: 'O', frequency: 750 },
  { letter: 'P', frequency: 192 },
  { letter: 'Q', frequency: 9 },
  { letter: 'R', frequency: 598 },
];

export const mockWords = [
  {
    term: '하다',
    definition: 'to do',
  },
  {
    term: '있다',
    definition: 'to be',
  },
  {
    term: '지다',
    definition: 'to become',
  },
  {
    term: '말하다',
    definition: 'to say',
  },
  {
    term: '오다',
    definition: 'to come',
  },
  {
    term: '가다',
    definition: 'to go',
  },
  {
    term: '보다',
    definition: 'to see',
  },
  {
    term: '보내다',
    definition: 'to send',
  },
  {
    term: '가지다',
    definition: 'to have',
  },
  {
    term: '기다리다',
    definition: 'to wait',
  },
  {
    term: '만나다',
    definition: 'to meet',
  },
  {
    term: '살다',
    definition: 'to live',
  },
  {
    term: '생각하다',
    definition: 'to think',
  },
  {
    term: '주다',
    definition: 'to give',
  },
  {
    term: '받다',
    definition: 'to receive',
  },
  {
    term: '알다',
    definition: 'to know',
  },
  {
    term: '만들다',
    definition: 'to make',
  },
  {
    term: '사용하다',
    definition: 'to use',
  },
  {
    term: '배우다',
    definition: 'to learn',
  },
  {
    term: '먹다',
    definition: 'to eat',
  },
  {
    term: '마시다',
    definition: 'to drink',
  },
  {
    term: '웃다',
    definition: 'to laugh',
  },
  {
    term: '읽다',
    definition: 'to read',
  },
  {
    term: '쓰다',
    definition: 'to write',
  },
];

export const cardData = [
  {
    id: '02SQ79MA0TDJQTzqi2p8',
    translation: 'This is The Care Senior Advisor Dawn Sun.',
    definitions: ['advisor dawn line'],
    minStart: 9,
    pos: 'Noun',
    sentence: '더 케어 시니어 어드바이저여명선입니다',
    start: 9,
    frequency: 999999,
    occurences: 1,
    minOrder: 1030,
    word: '어드바이저여명선',
    title: 'Parasite',
    length: 8,
  },
  {
    id: '02ZTqipMTvKmw4bwhCQm',
    title: 'Parasite',
    sentence: '경애하는 최고 령도자김정은 동지께서는 오늘',
    start: 5,
    length: 2,
    translation: 'My beloved oldest brother, Comrade Em Jeong-eun, said,',
    word: '최고',
    occurences: 1,
    minStart: 5,
    frequency: 999999,
    definitions: ['the oldest', 'the highest', 'top', 'the best'],
    pos: 'Noun',
    minOrder: 1534,
  },
  {
    id: '05PaWOQJ3Hy2a5A0lk1g',
    minStart: 5,
    title: 'Parasite',
    sentence: '야, 너 웬, 웬일이야?',
    minOrder: 148,
    word: '웬',
    translation: "Hey, what's up with you?",
    start: 5,
    frequency: 999999,
    definitions: ['what'],
    occurences: 1,
    pos: 'Noun',
    length: 1,
  },
  {
    id: '06Crkv6d8TJiV3Dvlt6Y',
    start: 0,
    sentence: '쓱 세팅을 하긴 했거든',
    translation: "I've set it up.",
    frequency: 8858,
    title: 'Parasite',
    definitions: [
      'on the quiet',
      'by stealth',
      'quietly',
      'stealthily',
      'furtively',
      'quickly',
      'lightly',
      'deftly',
      'quickly and quietly',
      'squeak',
    ],
    word: '쓱',
    occurences: 1,
    pos: 'Adverb',
    minStart: 0,
    length: 1,
    minOrder: 644,
  },
  {
    id: '06zlYPB4JA9SmXOPhhiZ',
    occurences: 1,
    minStart: 10,
    title: 'Parasite',
    minOrder: 2414,
    word: '갖추다',
    sentence: '문광 님을 예의를 갖춰서보내 드릴 수가 있었는데',
    translation: 'I could have sent Moon Kwang away with courtesy.',
    frequency: 591,
    length: 2,
    start: 10,
    definitions: [
      'to be equipped',
      'to be qualified',
      'to be complete',
      'to have',
      'to possess',
      'to meet',
      'to fit',
      'to satisfy',
      'to be equipped with',
    ],
    pos: 'Verb',
  },
  {
    id: '07cyhju8p0sYHpDPGmB0',
    minOrder: 462,
    pos: 'Verb',
    definitions: [
      'to have',
      'to hold',
      'to own',
      'to possess',
      'to keep',
      'to give',
      'to throw',
      'to convene',
      'to conceive',
      'to be pregnant',
      'to expect',
      'to use',
      'to target',
      'to harbor',
      'to have relationship with',
      'to interact',
    ],
    occurences: 2,
    sentence: '괜히 막 길 가다 멈춰 서 가지고',
    minStart: 15,
    start: 15,
    word: '가지다',
    frequency: 350,
    title: 'Parasite',
    translation: 'I just stopped on the street for no reason.',
    length: 2,
  },
  {
    id: '07eBh8dzYs1mLwSgPK0s',
    length: 3,
    frequency: 7221,
    definitions: ['architect'],
    minStart: 0,
    translation: "Do you know architect Namgung Hyunja?He's famous.",
    word: '건축가',
    pos: 'Noun',
    minOrder: 283,
    title: 'Parasite',
    occurences: 2,
    sentence: '건축가 남궁현자 선생님 아시나?유명한 분인데',
    start: 0,
  },
  {
    id: '0ENmprkwpABjhSWP7Fy0',
    minStart: 6,
    frequency: 999999,
    occurences: 1,
    sentence: '네, 처음 뵙, 네',
    minOrder: 804,
    translation: 'Yeah, nice to meet you. Yeah.',
    pos: 'Adverb',
    word: '뵙',
    definitions: ['see you'],
    length: 1,
    title: 'Parasite',
    start: 6,
  },
  {
    id: '0EzSEKPqt3LlSiIBHPvS',
    start: 4,
    definitions: [
      'to send out',
      'to dump',
      'to fire',
      'to air',
      'to publish',
      'to run',
      'to release',
    ],
    frequency: 3815,
    minOrder: 720,
    pos: 'Verb',
    word: '내보내다',
    translation: 'Can you send him out quietly, knight Yoon?',
    title: 'Parasite',
    length: 3,
    occurences: 1,
    sentence: '조용히 내보낼 수 있지, 윤 기사?',
    minStart: 4,
  },
  {
    id: '0G0y3nPFrYyhjKbR7Fly',
    length: 3,
    sentence: '채권자들 이제 몰려오면은숨는 비밀 방이다',
    minOrder: 1444,
    minStart: 0,
    start: 0,
    frequency: 999999,
    translation: "It's a secret room where creditors come in now.",
    definitions: ['creditor', 'creditors'],
    title: 'Parasite',
    occurences: 1,
    word: '채권자',
    pos: 'Noun',
  },
  {
    id: '0JMhnk0RO8Q7XSw4wsVI',
    start: 0,
    length: 2,
    title: 'Parasite',
    word: '건강',
    sentence: '건강들 하시고',
    pos: 'Noun',
    definitions: ['health', 'wellbeing'],
    frequency: 756,
    occurences: 6,
    minOrder: 180,
    translation: 'Stay healthy.',
    minStart: 0,
  },
  {
    id: '0NVwh7UmzBmRcTAbBJxR',
    definitions: [
      'to become happy',
      'to become delighted',
      'to become elated',
      'to be exciting',
    ],
    frequency: 23709,
    title: 'Parasite',
    occurences: 1,
    word: '신나다',
    translation: "Since we're going, let's have some fun, okay?",
    length: 2,
    minOrder: 1139,
    minStart: 12,
    start: 12,
    sentence: '이왕 가기로 한 거좀 신나게 가자, 어?',
    pos: 'Verb',
  },
  {
    id: '0NpBtzeL0NJ4w7SXhKFS',
    word: '팔다',
    start: 12,
    title: 'Parasite',
    frequency: 999999,
    minOrder: 2029,
    sentence: '사람을 죽이건 나라를 팔아먹건',
    pos: 'Verb',
    length: 1,
    minStart: 12,
    definitions: [
      'to sell',
      'to pimp',
      'to sell a woman',
      'to prostitute',
      'to get distracted',
      'to excuse',
      'to lie',
      'to betray',
      'to buy crops',
    ],
    occurences: 2,
    translation: 'Kill people or sell the country.',
  },
  {
    id: '0Os3jYfwGZ9op0dlJmy6',
    minOrder: 623,
    pos: 'Noun',
    title: 'Parasite',
    start: 10,
    definitions: ['benz'],
    sentence: '에이, 전철 말고 벤츠로 쭉 가시죠',
    occurences: 4,
    minStart: 10,
    translation: "Come on, let's go straight to Benz, not the subway.",
    length: 2,
    word: '벤츠',
    frequency: 999999,
  },
  {
    id: '0QL0IJFtLjUVAXrtCSk8',
    sentence: '각자 다른 향으로 해야 되지 않을까요?',
    minStart: 6,
    definitions: ['incense', 'scent', 'fragrance'],
    title: 'Parasite',
    minOrder: 1082,
    start: 6,
    pos: 'Noun',
    word: '향',
    length: 1,
    frequency: 999999,
    occurences: 1,
    translation: "Shouldn't we each use a different scent?",
  },
  {
    id: '0V1qSsMidze3HO6CkWJt',
    translation: '- Kanigamaboko, Japanese crab meat. - Oh, yeah.',
    length: 2,
    title: 'Parasite',
    sentence: "- '카니가마보코', 일본 게맛살-  아, 네",
    minStart: 3,
    definitions: ['carney'],
    minOrder: 1157,
    word: '카니',
    start: 3,
    frequency: 999999,
    occurences: 1,
    pos: 'Noun',
  },
  {
    id: '0VwEluDSELQpwnReqV8t',
    start: 13,
    pos: 'Noun',
    definitions: [
      'seniority',
      'predecessor',
      'appointing',
      'electing',
      'senior',
    ],
    minStart: 13,
    length: 2,
    minOrder: 2303,
    word: '선임',
    frequency: 13182,
    sentence: '저, 귀하께서는변호인을 선임할 권리가 있고',
    occurences: 2,
    translation: 'Well, you have the right to consult a lawyer.',
    title: 'Parasite',
  },
  {
    id: '0Wj0VqLoNwYsn1UuyeYr',
    frequency: 825,
    translation: 'We need to get something ready.',
    occurences: 2,
    length: 2,
    start: 7,
    definitions: ['preparation'],
    minOrder: 850,
    minStart: 7,
    sentence: '우리도 뭔가 준비를 해야겠다',
    word: '준비',
    title: 'Parasite',
    pos: 'Noun',
  },
  {
    id: '0aKYq7SBFCQ7RNJsgCcF',
    sentence: '훨씬 더 높은컴퓨팅 파워가 필요해서…',
    start: 0,
    definitions: ['by far', 'much', 'a lot', 'by a long way'],
    frequency: 999999,
    word: '훨씬',
    minOrder: 809,
    occurences: 1,
    length: 2,
    translation: 'I need much higher computing power…',
    minStart: 0,
    pos: 'Adverb',
    title: 'Parasite',
  },
  {
    id: '0b63w31Rr50kM9aOCTFh',
    frequency: 999999,
    title: 'Parasite',
    pos: 'Adverb',
    minOrder: 1973,
    start: 10,
    length: 1,
    translation: "Oh, my God, I'm dizzy.",
    occurences: 1,
    sentence: '아휴, 아씨, 어지럽네',
    word: '럽',
    definitions: ['love'],
    minStart: 10,
  },
  {
    id: '0bqe8x98FwBn0AnIuBUl',
    occurences: 1,
    frequency: 17810,
    sentence: '빈집에서 오래오래 버티느라고생을 좀 했지',
    pos: 'Noun',
    minOrder: 2410,
    translation: "I've had a long life in an empty house.",
    title: 'Parasite',
    definitions: ['vacant home', 'empty house', 'an empty house'],
    word: '빈집',
    start: 0,
    minStart: 0,
    length: 2,
  },
  {
    id: '0c0ZWklxtzCHTf5vTsKe',
    title: 'Parasite',
    word: '미행',
    start: 17,
    length: 2,
    sentence: '쯧, 근데 형사분들만괜히 우리 미행을 한다고',
    occurences: 2,
    minStart: 17,
    translation: 'Tsk, but only detectives follow us for nothing.',
    definitions: ['trailing', 'shadowing', 'good conduct', 'follow'],
    frequency: 31428,
    pos: 'Noun',
    minOrder: 2362,
  },
  {
    id: '0cnKOQRKsSzL9VksyzbV',
    frequency: 63172,
    length: 2,
    translation: 'Lee, a group order just coming in from Jusarang Church.',
    occurences: 1,
    minStart: 13,
    start: 13,
    pos: 'Noun',
    minOrder: 93,
    word: '주문',
    definitions: ['spells', 'order', 'direction', 'a magic formula'],
    title: 'Parasite',
    sentence: '이, 주사랑교회에서단체 주문이 막 들어오고 있는',
  },
  {
    id: '0hlf3LJLjb1qVwTvXF33',
    translation: "What's wrong with him? He'",
    length: 2,
    sentence: '쟤는 어째 센서가 제멋대로야',
    pos: 'Adverb',
    start: 3,
    frequency: 1371,
    minStart: 3,
    definitions: ['why', 'how', 'at a certain angle', 'so much', 'how can i'],
    minOrder: 1679,
    title: 'Parasite',
    occurences: 1,
    word: '어찌',
  },
  {
    id: '0j1plJ6ijx807oavTOyO',
    definitions: ['hygiene', 'sanitation'],
    start: 25,
    title: 'Parasite',
    length: 2,
    translation:
      "Oh, I'm just saying that from the perspective of public health or healthcare,",
    word: '위생',
    frequency: 6393,
    minOrder: 938,
    pos: 'Noun',
    minStart: 25,
    sentence: '아, 전 단지 그, 공중 보건 또는그, 보건 위생의 관점에서',
    occurences: 1,
  },
  {
    id: '0lp8B9frOHHT8kvsDuog',
    translation:
      'On top of this tablecloth, there are side dishes, rice grains, and red pepper paste.',
    start: 9,
    definitions: ['side dishes'],
    minStart: 9,
    word: '가반찬',
    minOrder: 431,
    sentence: '이 식탁보 위에다가반찬, 밥풀, 고추장 이런 걸로 아주',
    frequency: 999999,
    occurences: 1,
    length: 3,
    pos: 'Noun',
    title: 'Parasite',
  },
  {
    id: '0mAnucVutcaB63OCtWYO',
    title: 'Parasite',
    minOrder: 379,
    pos: 'Adverb',
    start: 4,
    frequency: 1366,
    definitions: [
      'quietly',
      'motionlessly',
      'indifferently',
      'deliberatey',
      'carefully',
      'silently',
      'still',
    ],
    translation: "I can't stay still for a second.",
    minStart: 4,
    length: 3,
    occurences: 1,
    word: '가만히',
    sentence: '한시도 가만히 있지를 못하거든',
  },
  {
    id: '0oZggIpGT6rUhiqwl8ZV',
    occurences: 1,
    sentence: '남궁현자 선생님의 예술혼이 숨어 있는',
    translation: "Where Namgoong Hyeonja's artistic spirit is hidden.",
    title: 'Parasite',
    start: 10,
    frequency: 999999,
    length: 3,
    minOrder: 1558,
    definitions: ['artistic spirit'],
    minStart: 10,
    word: '예술혼',
    pos: 'Noun',
  },
  {
    id: '0qDhiEi0llZhQ9Wyqss2',
    minStart: 4,
    definitions: ['house'],
    title: 'Parasite',
    pos: 'Noun',
    length: 2,
    translation: 'But thanks to the fact that the house was empty for a while,',
    word: '집이',
    start: 4,
    frequency: 999999,
    minOrder: 2411,
    sentence: '그래도 집이한동안 비어 있었던 덕분에',
    occurences: 1,
  },
  {
    id: '0qOFjX9cSsh3LkuImWte',
    translation: 'He said he was going to see Ki-woo.',
    title: 'Parasite',
    sentence: '기우 만나러 간다고 하니까',
    occurences: 7,
    start: 0,
    definitions: ['unfounded worry', 'tilted rain'],
    pos: 'Noun',
    length: 2,
    minOrder: 158,
    minStart: 0,
    word: '기우',
    frequency: 13584,
  },
  {
    id: '0tzttd0MMNSUopOFzVtm',
    word: '영작',
    occurences: 1,
    title: 'Parasite',
    translation: "Let's try to write English with that.",
    sentence: '우리 그걸로 영작을 한번 해 보자',
    start: 7,
    minOrder: 475,
    frequency: 999999,
    length: 2,
    minStart: 7,
    definitions: ['english composition'],
    pos: 'Noun',
  },
  {
    id: '0vj1HvGzAcJSz0VyZZU7',
    translation: "Dasong knows this. He's a scout.",
    start: 19,
    frequency: 999999,
    title: 'Parasite',
    occurences: 1,
    pos: 'Adverb',
    word: '까',
    minStart: 19,
    minOrder: 1680,
    sentence: '다송이는 이런 거 알 텐데스카우트니까',
    definitions: ['peel'],
    length: 1,
  },
  {
    id: '0xBHAZii6Iudq2aFlZLL',
    sentence: '잡힌다',
    word: '잡히다',
    occurences: 4,
    length: 2,
    pos: 'Verb',
    frequency: 21745,
    minStart: 0,
    start: 0,
    definitions: [
      'to be created',
      'to be formed',
      'to be arrested',
      'to be held',
      'to be caught',
      'to be butchered',
      'to be taken',
      'to be grabbed',
      'to be gotten',
      'to be landed',
      'to be established',
      'to be settled',
      'to be set',
      'to be gotten right',
      'to be kept in check',
      'to be still',
      'to be quiet',
      'to be figured out',
      'to be found',
      'to be captured',
      "to be caught in one's own words",
      'to be pawned',
      'to be estimated',
      'to be made',
      'to have someone hold something',
      'to have someone butcher an animal',
      'to get caught',
    ],
    translation: "I'm",
    title: 'Parasite',
    minOrder: 32,
  },
  {
    id: '100oMMvDY90s0xmvSwfH',
    translation: 'Kim, who is suspected of killing Park,',
    occurences: 1,
    length: 2,
    minStart: 5,
    minOrder: 2347,
    frequency: 8117,
    pos: 'Noun',
    title: 'Parasite',
    sentence: '박 대표 살해 혐의를 받고 있는김 씨는',
    definitions: ['murder', 'killing'],
    start: 5,
    word: '살해',
  },
  {
    id: '12VRQOExwid40hlDd6TG',
    definitions: ['dream', 'goal', 'wish', 'vain hope'],
    occurences: 1,
    sentence: '꿈을 꾼 거 같기도 하고',
    pos: 'Noun',
    start: 0,
    translation: "I feel like I've been dreaming.",
    word: '꿈',
    frequency: 49651,
    minOrder: 2397,
    title: 'Parasite',
    length: 1,
    minStart: 0,
  },
  {
    id: '12pWPSBPsGPx0xYF430M',
    length: 2,
    frequency: 608,
    start: 0,
    minOrder: 795,
    definitions: [
      'customer',
      'guest',
      'patron',
      'client',
      'clientele',
      'the client',
    ],
    translation: "Sir, how, you're talking too long?",
    title: 'Parasite',
    sentence: '고객님, 어떻게, 말씀이 길어지시네요?',
    minStart: 0,
    pos: 'Noun',
    occurences: 1,
    word: '고객',
  },
  {
    id: '14iZGldkNojqS3nrJKcB',
    minStart: 6,
    occurences: 19,
    frequency: 999999,
    sentence: '여보, 내 차 시트 밑에서 이런 게…',
    translation: 'Honey, under my car seat...',
    minOrder: 671,
    title: 'Parasite',
    word: '차',
    pos: 'Noun',
    length: 1,
    definitions: [
      'tea',
      'car',
      'automobile',
      'vehicle',
      'carload',
      'difference',
      'gap',
    ],
    start: 6,
  },
  {
    id: '14sXHdhTlVqz6XdMSQaR',
    title: 'Parasite',
    translation:
      "We're gonna use their stinky five-legged meat as the last nuclear dump site.",
    occurences: 1,
    pos: 'Verb',
    minStart: 27,
    length: 1,
    sentence: '저들의 구린내 나는 오장육부를최후의 핵폐기장으로 삼아',
    frequency: 55614,
    start: 27,
    minOrder: 1545,
    definitions: [
      'to adopt',
      'to have',
      'to take',
      'to use',
      'to consider',
      'to regard',
      'to think',
      'to deem',
    ],
    word: '삼다',
  },
  {
    id: '159m2dFj9kblPLA8n09V',
    minOrder: 824,
    title: 'Parasite',
    minStart: 2,
    length: 2,
    sentence: '한 집안의 가장',
    definitions: ['house', 'home', 'family'],
    pos: 'Noun',
    frequency: 999999,
    start: 2,
    translation: 'the head of a family',
    word: '집안',
    occurences: 1,
  },
  {
    id: '172ItnOmpnmUPF5kTxyT',
    title: 'Parasite',
    minOrder: 865,
    start: 10,
    word: '증상',
    translation: "No, I mean, if you're having this kind of symptom,",
    definitions: ['symptom'],
    occurences: 1,
    length: 2,
    frequency: 2254,
    sentence: '아니, 원래 이런 증상이이렇게 나타나면은',
    pos: 'Noun',
    minStart: 10,
  },
  {
    id: '19DcHjY6Ywb2TzQGqK1N',
    occurences: 24,
    minOrder: 226,
    length: 2,
    definitions: ['nice', 'fine', 'all right', 'okay', 'to be okay'],
    title: 'Parasite',
    pos: 'Adjective',
    frequency: 852,
    word: '괜찮다',
    translation: "Oh, it's gonna be okay. I'm just introducing myself.",
    start: 3,
    sentence: '아, 괜찮을 거야일단 내 소개로 가는 거니까',
    minStart: 3,
  },
  {
    id: '19mUbibd6xRlRMiNQnD4',
    translation: "You're all tangled up from the start.",
    length: 2,
    definitions: ['completeness', 'totally'],
    word: '완전',
    frequency: 59775,
    pos: 'Noun',
    title: 'Parasite',
    start: 8,
    minStart: 8,
    minOrder: 337,
    occurences: 13,
    sentence: '너는 시작부터 완전 엉킨 거야',
  },
  {
    id: '1CL308ZmirkJpZvyFUda',
    frequency: 999999,
    occurences: 1,
    word: '플러',
    length: 2,
    sentence: '저는 완전히 교수형 플러스능지처참이에요',
    minStart: 11,
    definitions: ['plush'],
    translation: "I'm a completely hanging plus.",
    title: 'Parasite',
    minOrder: 934,
    pos: 'Noun',
    start: 11,
  },
  {
    id: '1GZ6aWoV7PiQ0QuC5Wd7',
    minOrder: 764,
    definitions: ['driving', 'operation'],
    length: 2,
    translation: "You're driving easy, you're more decent.",
    word: '운전',
    start: 0,
    minStart: 0,
    pos: 'Noun',
    occurences: 1,
    frequency: 2943,
    title: 'Parasite',
    sentence: '운전도 살살들 하시고 더 점잖고',
  },
  {
    id: '1JMILQLGlYHGJZqigzPJ',
    title: 'Parasite',
    occurences: 2,
    sentence: '근데 그게너 문제 푸는 거랑 뭔 상관이야?',
    definitions: ['crab'],
    length: 1,
    start: 4,
    minOrder: 471,
    translation: 'But what does that have to do with solving your problems?',
    frequency: 17274,
    minStart: 4,
    pos: 'Noun',
    word: '게',
  },
  {
    id: '1PNQQIoZHFTckUdaNONL',
    length: 2,
    occurences: 1,
    frequency: 999999,
    pos: 'Adjective',
    minOrder: 1156,
    sentence: '그렇죠, 그리고 푸푸는',
    minStart: 9,
    word: '푸푸다',
    translation: 'Yes, and Pooh...',
    start: 9,
    definitions: ['pooh'],
    title: 'Parasite',
  },
  {
    id: '1VBU6RFk6jqoWpzeImWC',
    title: 'Parasite',
    length: 2,
    definitions: ['madam'],
    frequency: 999999,
    occurences: 22,
    minStart: 7,
    translation: "Well, the wife of the house, she'sir.",
    sentence: '씁, 그 집 사모님이 뭐랄까',
    pos: 'Noun',
    word: '사모',
    minOrder: 228,
    start: 7,
  },
  {
    id: '1W2oa5FfKTBN6Dv83fRy',
    translation: "You've taken the college entrance exam four times in total.",
    occurences: 3,
    definitions: ['national college entrance exam', 'csat'],
    frequency: 8346,
    start: 8,
    word: '수능',
    minStart: 8,
    title: 'Parasite',
    pos: 'Noun',
    minOrder: 216,
    length: 2,
    sentence: '도합 네 번의 수능을 봤잖아?',
  },
  {
    id: '1WESoJWMs9Pr7stJcgeJ',
    minOrder: 787,
    length: 2,
    translation: 'Sort of like, a belt of faith?',
    pos: 'Noun',
    frequency: 1475,
    start: 0,
    occurences: 3,
    word: '일종',
    title: 'Parasite',
    minStart: 0,
    definitions: ['kind', 'sort', 'kind of'],
    sentence: '일종의 뭐랄까, 믿음의 벨트?',
  },
  {
    id: '1WabZ3Kr1EMiPdxzHzFc',
    translation: "Oh, I've been doing this day by day.",
    minStart: 11,
    title: 'Parasite',
    start: 11,
    pos: 'Adverb',
    definitions: ['luharu'],
    occurences: 1,
    word: '루하루',
    length: 3,
    frequency: 999999,
    minOrder: 829,
    sentence: '아, 이런 마음으로하루하루 해 왔습니다',
  },
  {
    id: '1Y0kMukfkj9YOBbFOerm',
    pos: 'Noun',
    minStart: 10,
    translation:
      'Korea is currently the number one tuberculosis outbreak rate.among OECD countries',
    definitions: ['occurrence', 'outbreak'],
    sentence: '한국이 현재 결핵 발생률 1위랍니다OECD 국가들 중의',
    minOrder: 909,
    frequency: 1865,
    title: 'Parasite',
    occurences: 2,
    start: 10,
    length: 2,
    word: '발생',
  },
  {
    id: '1ZElBg1IydrHlkV04D3W',
    sentence: '이 사건 범행을 깊이 뉘우치며…',
    start: 12,
    occurences: 1,
    translation: 'I deeply regret the crime in this case.',
    minStart: 12,
    minOrder: 2328,
    frequency: 8232,
    length: 3,
    definitions: ['to introspect', 'to examine oneself', 'to repent'],
    word: '뉘우치다',
    title: 'Parasite',
    pos: 'Verb',
  },
  {
    id: '1ZYOq9yDAxkMD3nrg4U1',
    frequency: 1135,
    start: 12,
    word: '선배',
    sentence: '♪ 일리노이 시카고과 선배는 김진모, 그는 네 사촌 ♪',
    occurences: 2,
    title: 'Parasite',
    length: 2,
    pos: 'Noun',
    definitions: ['senior', 'veteran', 'older alumnus'],
    translation: "♪ Illinois and Chicago senior Kim Jin-mo, he's your cousin ♪",
    minStart: 12,
    minOrder: 429,
  },
  {
    id: '1aSy2R7pcLjmdTvYW6Hn',
    occurences: 1,
    minOrder: 2427,
    start: 0,
    length: 3,
    pos: 'Noun',
    sentence: '붙박이 가정부가24시간 집에 있다 보니까',
    minStart: 0,
    frequency: 14355,
    word: '붙박이',
    definitions: ['fixture', 'being built-in', 'built-in'],
    title: 'Parasite',
    translation: 'A built-in housekeeper stays at home 24 hours a day.',
  },
  {
    id: '1asy8eNw2RYOJFUHuVSG',
    word: '사실',
    minStart: 14,
    sentence: '잘 아시겠지만 민혁 쌤이 사실',
    occurences: 7,
    length: 2,
    start: 14,
    title: 'Parasite',
    translation: "I'm sure you know, but teacher Minhyuk actually...",
    pos: 'Adverb',
    frequency: 55302,
    minOrder: 303,
    definitions: ['actually', 'as a matter of fact', 'de facto', 'in fact'],
  },
  {
    id: '1bQXIdE8iOrrhJzJiUwM',
    definitions: ['nasty smell', 'stink', 'stinky smell'],
    occurences: 1,
    sentence: '저들의 구린내 나는 오장육부를최후의 핵폐기장으로 삼아',
    pos: 'Noun',
    frequency: 17521,
    translation:
      "We're gonna use their stinky five-legged meat as the last nuclear dump site.",
    length: 3,
    title: 'Parasite',
    minOrder: 1545,
    word: '구린내',
    start: 4,
    minStart: 4,
  },
  {
    id: '1beFPi848Dv2j14HJI7r',
    definitions: ['wolf'],
    frequency: 7704,
    occurences: 1,
    title: 'Parasite',
    translation: 'Our engineering student, the wolf pups, walking around Hye.',
    sentence: '우리 과 공대생 그 늑대 새끼들이다혜 근처에 얼씬거리는 거 자체가',
    length: 2,
    start: 11,
    minOrder: 199,
    pos: 'Noun',
    minStart: 11,
    word: '늑대',
  },
  {
    id: '1f3F8qdVCF3xVcZfFPl1',
    length: 2,
    minOrder: 352,
    start: 18,
    occurences: 12,
    minStart: 18,
    title: 'Parasite',
    word: '시간',
    pos: 'Noun',
    definitions: ['time', 'hours'],
    frequency: 57430,
    sentence: '수업은 월, 수, 금세 번, 두 시간씩 괜찮죠?',
    translation:
      'The classes are available for two hours, three times a month, Wednesday, and soon, right?',
  },
  {
    id: '1f5lTHKwiP9qUOYKFEvx',
    translation:
      'I was appalled and outraged by their vicious and low-level provocation.',
    pos: 'Verb',
    sentence:
      '그들의 악랄하고 저급한 도발에 대해서경악과 분노를 금치 못하시었다',
    length: 2,
    title: 'Parasite',
    minStart: 28,
    start: 28,
    frequency: 5129,
    word: '금하다',
    definitions: ['to prohibit', 'to ban', 'to suppress', 'to forbid'],
    minOrder: 1536,
    occurences: 1,
  },
  {
    id: '1fQdnGWkgFDcx4FxOKXh',
    length: 3,
    sentence: '자, 이렇게 우리 모처럼들이렇게 둘러앉아 가지고, 어',
    word: '둘러앉다',
    translation:
      "Now, let's sit around like this for the first time in a while, uh...",
    start: 18,
    definitions: ['to sit round', 'to sit around'],
    occurences: 1,
    minStart: 18,
    minOrder: 115,
    frequency: 9171,
    title: 'Parasite',
    pos: 'Verb',
  },
  {
    id: '1fWKsEUl7qn21YECqKog',
    pos: 'Noun',
    sentence: '마침내 비핵화와세계 평화를 이룩하시려는',
    word: '핵화',
    minOrder: 1546,
    minStart: 5,
    occurences: 1,
    frequency: 999999,
    title: 'Parasite',
    definitions: ['nuclearization'],
    translation:
      "Finally, you're trying to achieve denuclearization and world peace.",
    length: 2,
    start: 5,
  },
  {
    id: '1mXtF8HTAyFU1VUHbmO5',
    length: 2,
    frequency: 999999,
    pos: 'Noun',
    word: '아메',
    definitions: ['amé'],
    translation: "American Indian, yes, it's a good thing.",
    occurences: 1,
    minOrder: 389,
    sentence: '아메리칸 인디언 맞아요, 좋은 거죠',
    start: 0,
    minStart: 0,
    title: 'Parasite',
  },
  {
    id: '1mf63uZUA0wu7q81VZ3K',
    length: 3,
    start: 7,
    frequency: 999999,
    minOrder: 808,
    title: 'Parasite',
    pos: 'Noun',
    translation: 'Now this is more than a mobile phone.',
    sentence: '지금 요거는 모바일 폰보다',
    minStart: 7,
    word: '모바일',
    definitions: ['mobile'],
    occurences: 1,
  },
  {
    id: '1qTKVpUMLySDaThn36ib',
    minOrder: 1991,
    minStart: 0,
    title: 'Parasite',
    frequency: 999999,
    length: 1,
    occurences: 1,
    translation: 'Choongsook said,',
    definitions: ['loyalty', 'allegiance', 'chung'],
    pos: 'Noun',
    start: 0,
    word: '충',
    sentence: '충숙이 언니가',
  },
  {
    id: '1rtQZlzgQxaR8V1nLo0r',
    translation: 'Sometimes, you know, it smells like that on the subway.',
    title: 'Parasite',
    word: '가끔',
    frequency: 21783,
    minOrder: 1857,
    pos: 'Adverb',
    minStart: 0,
    definitions: ['sometimes'],
    occurences: 2,
    sentence: '가끔 그, 지하철 타면 나는 냄새 있어그런 거랑 비슷해',
    length: 2,
    start: 0,
  },
  {
    id: '1smhUhkkAg8arLw35TYc',
    start: 11,
    translation: "- Shh. She's still asleep. - Yeah, yeah.",
    title: 'Parasite',
    word: '자요',
    definitions: ['go to bed'],
    minOrder: 2111,
    frequency: 999999,
    occurences: 1,
    length: 2,
    pos: 'Noun',
    minStart: 11,
    sentence: '- 쉿, 애가 아직 자요-  네, 네',
  },
  {
    id: '1vJDWgIU3hmFUkdmnq0I',
    title: 'Parasite',
    minOrder: 48,
    word: '속도',
    occurences: 1,
    length: 2,
    frequency: 56751,
    translation: 'If we do it at this speed,',
    minStart: 6,
    start: 6,
    pos: 'Noun',
    definitions: ['speed'],
    sentence: '우리도 이 속도로 하면',
  },
  {
    id: '1vK350qiHUd04p3yA4pc',
    minOrder: 1400,
    minStart: 9,
    pos: 'Noun',
    translation: "Look, he's a good man, and thanks to him...",
    length: 3,
    frequency: 999999,
    word: '셔저분',
    start: 9,
    title: 'Parasite',
    sentence: '저기, 좋은 분이셔저분 덕분에 여기 들어온…',
    definitions: ['mr. sherzer'],
    occurences: 1,
  },
  {
    id: '1wn9ERGySluLNhtmshTB',
    translation: 'So until then, I want you to take good care of him.',
    title: 'Parasite',
    start: 5,
    definitions: ['that time', 'that moment', 'then'],
    occurences: 5,
    frequency: 49113,
    sentence: '그러니까 그때까지만네가 잘 좀 챙겨 줘라',
    word: '그때',
    pos: 'Noun',
    minStart: 5,
    length: 2,
    minOrder: 207,
  },
  {
    id: '1x0dA9LGTzIQSKrzolfs',
    sentence: '손 번쩍',
    pos: 'Adverb',
    minStart: 2,
    occurences: 1,
    start: 2,
    minOrder: 1549,
    length: 2,
    frequency: 8631,
    word: '번쩍',
    title: 'Parasite',
    definitions: [
      'in a sparkle',
      'interestingly',
      'easily',
      'without effort',
      'aloft',
      'high and lightly',
      'all of a sudden',
      'flashing',
    ],
    translation: 'Raise your hand',
  },
  {
    id: '23sZQMnz01gnggSBlSUa',
    minOrder: 1103,
    frequency: 3261,
    title: 'Parasite',
    start: 17,
    occurences: 1,
    definitions: ['game', 'joke', 'fun', 'trick'],
    word: '장난',
    length: 2,
    minStart: 17,
    translation: "It's a lot of money coming over to my house, yeah.",
    pos: 'Noun',
    sentence: '우리 집으로 넘어오는 돈이이게 장난이 아니야, 응',
  },
  {
    id: '25VngcxfCNRlDhYZU9ic',
    definitions: ['truly', 'sincerely', 'indeed'],
    minStart: 0,
    length: 3,
    translation: "It's really timely, huh?",
    start: 0,
    occurences: 1,
    frequency: 999999,
    word: '참으로',
    minOrder: 172,
    sentence: '참으로 시의적절하다, 어',
    title: 'Parasite',
    pos: 'Adverb',
  },
  {
    id: '25wuWzaej71fCr7qXYDF',
    word: '자리',
    start: 5,
    occurences: 4,
    minOrder: 548,
    frequency: 10549,
    title: 'Parasite',
    pos: 'Noun',
    sentence: '아니요, 자리 좀 비켜 줘요',
    translation: 'No, no, no, no, no, no, no, no, no, no.',
    definitions: [
      'space',
      'place',
      'spot',
      'aftermath',
      'seat',
      'position',
      'post',
      'opening',
      'position as a spouse',
      'venue',
      'occasion',
      'digit',
      'mat',
      'bed',
      'bedding',
    ],
    minStart: 5,
    length: 2,
  },
  {
    id: '29cG3xi4bCwNPGi3WYuO',
    frequency: 999999,
    start: 7,
    sentence: '아, 아유, 아유그냥 쌤은 요까지만 아세요',
    length: 3,
    occurences: 1,
    translation: 'Oh, no, no, no, no, no, no, no, no, no, no, no',
    definitions: ['oh, my'],
    minOrder: 754,
    title: 'Parasite',
    word: '아유그',
    pos: 'Noun',
    minStart: 7,
  },
  {
    id: '29qZe0wLXuQxlZSVQu7a',
    word: '똥물',
    frequency: 37413,
    definitions: ['fecal water', 'vomiting bile', 'dung water'],
    title: 'Parasite',
    sentence: '넌 여기 그냥 있어여기 똥물이야, 똥물',
    occurences: 2,
    length: 2,
    start: 13,
    pos: 'Noun',
    minOrder: 1955,
    translation: "You're just here. You're a shithead.",
    minStart: 13,
  },
  {
    id: '2FvYrz22QkQMFsmiOFPj',
    minOrder: 1129,
    word: '구름',
    title: 'Parasite',
    occurences: 2,
    frequency: 1709,
    sentence: '약간의 구름 이동 중',
    minStart: 4,
    length: 2,
    start: 4,
    definitions: ['cloud'],
    pos: 'Noun',
    translation: 'A little cloud movement.',
  },
  {
    id: '2L7fZnplhQkN6aIjLeuw',
    length: 2,
    pos: 'Noun',
    start: 0,
    title: 'Parasite',
    frequency: 584,
    definitions: ['child', 'kid', 'cutie pie', 'descendent'],
    sentence: '자식, 밖에 안 덥나',
    occurences: 3,
    word: '자식',
    minStart: 0,
    minOrder: 1164,
    translation: "Dude, isn't it hot outside?",
  },
  {
    id: '2LbRxuczbJueYy0I9PXY',
    definitions: [
      'to go out',
      'to leave',
      'to go forward',
      'to be spread',
      'to be revealed',
      'to become known',
      'to begin action',
      'to work',
      'to go',
      'to attend',
      'to participate',
      'to run for',
      'to maintain a certain attitude',
      'to be worth',
      'to weigh',
      'to spend',
      'to receive',
      'to be worn out',
      'to break',
      'to injure',
      'to become unconscious',
      'to recover',
      'to be taken',
      'to be sold',
      'to go off',
      'to work well',
      'to go to work',
      'to move',
      'to progress',
      'to proceed',
      'to go outside',
    ],
    occurences: 3,
    pos: 'Verb',
    word: '나가다',
    translation: '- Mother, get out of here. - Oh.',
    minOrder: 514,
    minStart: 8,
    frequency: 323,
    title: 'Parasite',
    length: 2,
    start: 8,
    sentence: '-  어머님은 나가 주세요-  아유',
  },
  {
    id: '2NoYJLqSA6x3jKbw990K',
    pos: 'Noun',
    length: 2,
    occurences: 1,
    minOrder: 999,
    word: '위주',
    sentence: '멤버십 위주로만 운영이 되고요',
    title: 'Parasite',
    minStart: 4,
    translation: "It's based on membership only.",
    definitions: ['center', 'focus', 'focusing on'],
    frequency: 1761,
    start: 4,
  },
  {
    id: '2OScnQJLw49TuPlQ6QNE',
    minOrder: 488,
    title: 'Parasite',
    pos: 'Adjective',
    occurences: 1,
    length: 2,
    translation: 'Jessica was really pretty, right?',
    word: '이쁘다',
    sentence: '아, 제시카 쌤 되게 이쁘던데, 그렇죠?',
    minStart: 12,
    start: 12,
    definitions: [
      'pretty',
      'beautiful',
      'comely',
      'adorable',
      'nice',
      'good',
      "it's pretty",
    ],
    frequency: 8880,
  },
];
