export const binData = [
  {
    bin: 0,
    bins: [
      { bin: 0, count: 48 },
      { bin: 1, count: 29 },
      { bin: 2, count: 74 },
      { bin: 3, count: 86 },
      { bin: 4, count: 35 },
      { bin: 5, count: 96 },
      { bin: 6, count: 55 },
    ],
  },
  {
    bin: 1,
    bins: [
      { bin: 0, count: 0 },
      { bin: 1, count: 33 },
      { bin: 2, count: 97 },
      { bin: 3, count: 24 },
      { bin: 4, count: 42 },
      { bin: 5, count: 55 },
      { bin: 6, count: 55 },
    ],
  },
  {
    bin: 2,
    bins: [
      { bin: 0, count: 53 },
      { bin: 1, count: 79 },
      { bin: 2, count: 18 },
      { bin: 3, count: 11 },
      { bin: 4, count: 16 },
      { bin: 5, count: 57 },
      { bin: 6, count: 4 },
    ],
  },
  {
    bin: 3,
    bins: [
      { bin: 0, count: 42 },
      { bin: 1, count: 28 },
      { bin: 2, count: 63 },
      { bin: 3, count: 90 },
      { bin: 4, count: 39 },
      { bin: 5, count: 21 },
      { bin: 6, count: 74 },
    ],
  },
  {
    bin: 4,
    bins: [
      { bin: 0, count: 1 },
      { bin: 1, count: 96 },
      { bin: 2, count: 22 },
      { bin: 3, count: 5 },
      { bin: 4, count: 83 },
      { bin: 5, count: 88 },
      { bin: 6, count: 29 },
    ],
  },
  {
    bin: 5,
    bins: [
      { bin: 0, count: 86 },
      { bin: 1, count: 87 },
      { bin: 2, count: 44 },
      { bin: 3, count: 14 },
      { bin: 4, count: 44 },
      { bin: 5, count: 5 },
      { bin: 6, count: 25 },
    ],
  },
  {
    bin: 6,
    bins: [
      { bin: 0, count: 76 },
      { bin: 1, count: 74 },
      { bin: 2, count: 19 },
      { bin: 3, count: 81 },
      { bin: 4, count: 44 },
      { bin: 5, count: 13 },
      { bin: 6, count: 39 },
    ],
  },
  {
    bin: 7,
    bins: [
      { bin: 0, count: 48 },
      { bin: 1, count: 99 },
      { bin: 2, count: 53 },
      { bin: 3, count: 41 },
      { bin: 4, count: 89 },
      { bin: 5, count: 56 },
      { bin: 6, count: 67 },
    ],
  },
  {
    bin: 8,
    bins: [
      { bin: 0, count: 36 },
      { bin: 1, count: 16 },
      { bin: 2, count: 30 },
      { bin: 3, count: 22 },
      { bin: 4, count: 33 },
      { bin: 5, count: 25 },
      { bin: 6, count: 79 },
    ],
  },
  {
    bin: 9,
    bins: [
      { bin: 0, count: 8 },
      { bin: 1, count: 76 },
      { bin: 2, count: 40 },
      { bin: 3, count: 7 },
      { bin: 4, count: 16 },
      { bin: 5, count: 51 },
      { bin: 6, count: 58 },
    ],
  },
  {
    bin: 10,
    bins: [
      { bin: 0, count: 38 },
      { bin: 1, count: 22 },
      { bin: 2, count: 24 },
      { bin: 3, count: 19 },
      { bin: 4, count: 34 },
      { bin: 5, count: 76 },
      { bin: 6, count: 35 },
    ],
  },
  {
    bin: 11,
    bins: [
      { bin: 0, count: 63 },
      { bin: 1, count: 94 },
      { bin: 2, count: 15 },
      { bin: 3, count: 56 },
      { bin: 4, count: 40 },
      { bin: 5, count: 57 },
      { bin: 6, count: 12 },
    ],
  },
  {
    bin: 12,
    bins: [
      { bin: 0, count: 10 },
      { bin: 1, count: 77 },
      { bin: 2, count: 16 },
      { bin: 3, count: 66 },
      { bin: 4, count: 76 },
      { bin: 5, count: 36 },
      { bin: 6, count: 82 },
    ],
  },
  {
    bin: 13,
    bins: [
      { bin: 0, count: 81 },
      { bin: 1, count: 62 },
      { bin: 2, count: 3 },
      { bin: 3, count: 88 },
      { bin: 4, count: 78 },
      { bin: 5, count: 1 },
      { bin: 6, count: 96 },
    ],
  },
  {
    bin: 14,
    bins: [
      { bin: 0, count: 14 },
      { bin: 1, count: 66 },
      { bin: 2, count: 97 },
      { bin: 3, count: 78 },
      { bin: 4, count: 45 },
      { bin: 5, count: 36 },
      { bin: 6, count: 45 },
    ],
  },
  {
    bin: 15,
    bins: [
      { bin: 0, count: 29 },
      { bin: 1, count: 38 },
      { bin: 2, count: 69 },
      { bin: 3, count: 83 },
      { bin: 4, count: 90 },
      { bin: 5, count: 33 },
      { bin: 6, count: 75 },
    ],
  },
  {
    bin: 16,
    bins: [
      { bin: 0, count: 67 },
      { bin: 1, count: 92 },
      { bin: 2, count: 26 },
      { bin: 3, count: 97 },
      { bin: 4, count: 65 },
      { bin: 5, count: 54 },
      { bin: 6, count: 15 },
    ],
  },
  {
    bin: 17,
    bins: [
      { bin: 0, count: 50 },
      { bin: 1, count: 12 },
      { bin: 2, count: 69 },
      { bin: 3, count: 72 },
      { bin: 4, count: 71 },
      { bin: 5, count: 76 },
      { bin: 6, count: 52 },
    ],
  },
  {
    bin: 18,
    bins: [
      { bin: 0, count: 96 },
      { bin: 1, count: 17 },
      { bin: 2, count: 29 },
      { bin: 3, count: 4 },
      { bin: 4, count: 65 },
      { bin: 5, count: 25 },
      { bin: 6, count: 15 },
    ],
  },
  {
    bin: 19,
    bins: [
      { bin: 0, count: 13 },
      { bin: 1, count: 82 },
      { bin: 2, count: 16 },
      { bin: 3, count: 67 },
      { bin: 4, count: 97 },
      { bin: 5, count: 87 },
      { bin: 6, count: 23 },
    ],
  },
  {
    bin: 20,
    bins: [
      { bin: 0, count: 13 },
      { bin: 1, count: 65 },
      { bin: 2, count: 76 },
      { bin: 3, count: 60 },
      { bin: 4, count: 62 },
      { bin: 5, count: 50 },
      { bin: 6, count: 50 },
    ],
  },
  {
    bin: 21,
    bins: [
      { bin: 0, count: 75 },
      { bin: 1, count: 82 },
      { bin: 2, count: 35 },
      { bin: 3, count: 95 },
      { bin: 4, count: 37 },
      { bin: 5, count: 92 },
      { bin: 6, count: 76 },
    ],
  },
  {
    bin: 22,
    bins: [
      { bin: 0, count: 53 },
      { bin: 1, count: 66 },
      { bin: 2, count: 37 },
      { bin: 3, count: 5 },
      { bin: 4, count: 32 },
      { bin: 5, count: 7 },
      { bin: 6, count: 23 },
    ],
  },
  {
    bin: 23,
    bins: [
      { bin: 0, count: 54 },
      { bin: 1, count: 83 },
      { bin: 2, count: 85 },
      { bin: 3, count: 13 },
      { bin: 4, count: 30 },
      { bin: 5, count: 32 },
      { bin: 6, count: 18 },
    ],
  },
  {
    bin: 24,
    bins: [
      { bin: 0, count: 37 },
      { bin: 1, count: 52 },
      { bin: 2, count: 37 },
      { bin: 3, count: 62 },
      { bin: 4, count: 47 },
      { bin: 5, count: 6 },
      { bin: 6, count: 17 },
    ],
  },
  {
    bin: 25,
    bins: [
      { bin: 0, count: 16 },
      { bin: 1, count: 30 },
      { bin: 2, count: 97 },
      { bin: 3, count: 80 },
      { bin: 4, count: 12 },
      { bin: 5, count: 54 },
      { bin: 6, count: 95 },
    ],
  },
  {
    bin: 26,
    bins: [
      { bin: 0, count: 29 },
      { bin: 1, count: 71 },
      { bin: 2, count: 7 },
      { bin: 3, count: 6 },
      { bin: 4, count: 34 },
      { bin: 5, count: 90 },
      { bin: 6, count: 77 },
    ],
  },
  {
    bin: 27,
    bins: [
      { bin: 0, count: 13 },
      { bin: 1, count: 9 },
      { bin: 2, count: 4 },
      { bin: 3, count: 45 },
      { bin: 4, count: 74 },
      { bin: 5, count: 99 },
      { bin: 6, count: 39 },
    ],
  },
  {
    bin: 28,
    bins: [
      { bin: 0, count: 23 },
      { bin: 1, count: 66 },
      { bin: 2, count: 10 },
      { bin: 3, count: 23 },
      { bin: 4, count: 43 },
      { bin: 5, count: 13 },
      { bin: 6, count: 1 },
    ],
  },
  {
    bin: 29,
    bins: [
      { bin: 0, count: 60 },
      { bin: 1, count: 77 },
      { bin: 2, count: 44 },
      { bin: 3, count: 37 },
      { bin: 4, count: 60 },
      { bin: 5, count: 54 },
      { bin: 6, count: 54 },
    ],
  },
  {
    bin: 30,
    bins: [
      { bin: 0, count: 76 },
      { bin: 1, count: 78 },
      { bin: 2, count: 98 },
      { bin: 3, count: 77 },
      { bin: 4, count: 21 },
      { bin: 5, count: 22 },
      { bin: 6, count: 98 },
    ],
  },
  {
    bin: 31,
    bins: [
      { bin: 0, count: 98 },
      { bin: 1, count: 84 },
      { bin: 2, count: 17 },
      { bin: 3, count: 96 },
      { bin: 4, count: 40 },
      { bin: 5, count: 21 },
      { bin: 6, count: 43 },
    ],
  },
  {
    bin: 32,
    bins: [
      { bin: 0, count: 50 },
      { bin: 1, count: 31 },
      { bin: 2, count: 52 },
      { bin: 3, count: 82 },
      { bin: 4, count: 94 },
      { bin: 5, count: 18 },
      { bin: 6, count: 62 },
    ],
  },
  {
    bin: 33,
    bins: [
      { bin: 0, count: 42 },
      { bin: 1, count: 22 },
      { bin: 2, count: 89 },
      { bin: 3, count: 52 },
      { bin: 4, count: 45 },
      { bin: 5, count: 63 },
      { bin: 6, count: 26 },
    ],
  },
  {
    bin: 34,
    bins: [
      { bin: 0, count: 97 },
      { bin: 1, count: 92 },
      { bin: 2, count: 13 },
      { bin: 3, count: 83 },
      { bin: 4, count: 6 },
      { bin: 5, count: 44 },
      { bin: 6, count: 48 },
    ],
  },
  {
    bin: 35,
    bins: [
      { bin: 0, count: 87 },
      { bin: 1, count: 12 },
      { bin: 2, count: 89 },
      { bin: 3, count: 46 },
      { bin: 4, count: 78 },
      { bin: 5, count: 28 },
      { bin: 6, count: 76 },
    ],
  },
  {
    bin: 36,
    bins: [
      { bin: 0, count: 67 },
      { bin: 1, count: 63 },
      { bin: 2, count: 49 },
      { bin: 3, count: 33 },
      { bin: 4, count: 89 },
      { bin: 5, count: 30 },
      { bin: 6, count: 88 },
    ],
  },
  {
    bin: 37,
    bins: [
      { bin: 0, count: 10 },
      { bin: 1, count: 97 },
      { bin: 2, count: 49 },
      { bin: 3, count: 68 },
      { bin: 4, count: 9 },
      { bin: 5, count: 55 },
      { bin: 6, count: 76 },
    ],
  },
  {
    bin: 38,
    bins: [
      { bin: 0, count: 19 },
      { bin: 1, count: 94 },
      { bin: 2, count: 38 },
      { bin: 3, count: 10 },
      { bin: 4, count: 41 },
      { bin: 5, count: 83 },
      { bin: 6, count: 79 },
    ],
  },
  {
    bin: 39,
    bins: [
      { bin: 0, count: 85 },
      { bin: 1, count: 45 },
      { bin: 2, count: 80 },
      { bin: 3, count: 61 },
      { bin: 4, count: 92 },
      { bin: 5, count: 72 },
      { bin: 6, count: 95 },
    ],
  },
  {
    bin: 40,
    bins: [
      { bin: 0, count: 80 },
      { bin: 1, count: 64 },
      { bin: 2, count: 49 },
      { bin: 3, count: 45 },
      { bin: 4, count: 31 },
      { bin: 5, count: 74 },
      { bin: 6, count: 51 },
    ],
  },
  {
    bin: 41,
    bins: [
      { bin: 0, count: 61 },
      { bin: 1, count: 9 },
      { bin: 2, count: 16 },
      { bin: 3, count: 60 },
      { bin: 4, count: 20 },
      { bin: 5, count: 23 },
      { bin: 6, count: 84 },
    ],
  },
  {
    bin: 42,
    bins: [
      { bin: 0, count: 42 },
      { bin: 1, count: 87 },
      { bin: 2, count: 69 },
      { bin: 3, count: 59 },
      { bin: 4, count: 89 },
      { bin: 5, count: 37 },
      { bin: 6, count: 4 },
    ],
  },
  {
    bin: 43,
    bins: [
      { bin: 0, count: 71 },
      { bin: 1, count: 97 },
      { bin: 2, count: 85 },
      { bin: 3, count: 21 },
      { bin: 4, count: 99 },
      { bin: 5, count: 77 },
      { bin: 6, count: 62 },
    ],
  },
  {
    bin: 44,
    bins: [
      { bin: 0, count: 12 },
      { bin: 1, count: 28 },
      { bin: 2, count: 6 },
      { bin: 3, count: 89 },
      { bin: 4, count: 74 },
      { bin: 5, count: 62 },
      { bin: 6, count: 89 },
    ],
  },
  {
    bin: 45,
    bins: [
      { bin: 0, count: 53 },
      { bin: 1, count: 2 },
      { bin: 2, count: 79 },
      { bin: 3, count: 73 },
      { bin: 4, count: 90 },
      { bin: 5, count: 50 },
      { bin: 6, count: 75 },
    ],
  },
  {
    bin: 46,
    bins: [
      { bin: 0, count: 32 },
      { bin: 1, count: 14 },
      { bin: 2, count: 83 },
      { bin: 3, count: 16 },
      { bin: 4, count: 30 },
      { bin: 5, count: 65 },
      { bin: 6, count: 34 },
    ],
  },
  {
    bin: 47,
    bins: [
      { bin: 0, count: 15 },
      { bin: 1, count: 8 },
      { bin: 2, count: 54 },
      { bin: 3, count: 34 },
      { bin: 4, count: 96 },
      { bin: 5, count: 76 },
      { bin: 6, count: 23 },
    ],
  },
  {
    bin: 48,
    bins: [
      { bin: 0, count: 5 },
      { bin: 1, count: 5 },
      { bin: 2, count: 91 },
      { bin: 3, count: 64 },
      { bin: 4, count: 99 },
      { bin: 5, count: 91 },
      { bin: 6, count: 51 },
    ],
  },
  {
    bin: 49,
    bins: [
      { bin: 0, count: 50 },
      { bin: 1, count: 49 },
      { bin: 2, count: 64 },
      { bin: 3, count: 46 },
      { bin: 4, count: 84 },
      { bin: 5, count: 61 },
      { bin: 6, count: 96 },
    ],
  },
  {
    bin: 50,
    bins: [
      { bin: 0, count: 40 },
      { bin: 1, count: 60 },
      { bin: 2, count: 50 },
      { bin: 3, count: 28 },
      { bin: 4, count: 73 },
      { bin: 5, count: 90 },
      { bin: 6, count: 9 },
    ],
  },
  {
    bin: 51,
    bins: [
      { bin: 0, count: 98 },
      { bin: 1, count: 9 },
      { bin: 2, count: 57 },
      { bin: 3, count: 67 },
      { bin: 4, count: 8 },
      { bin: 5, count: 78 },
      { bin: 6, count: 79 },
    ],
  },
  {
    bin: 52,
    bins: [
      { bin: 0, count: 71 },
      { bin: 1, count: 87 },
      { bin: 2, count: 69 },
      { bin: 3, count: 2 },
      { bin: 4, count: 89 },
      { bin: 5, count: 18 },
      { bin: 6, count: 86 },
    ],
  },
];

export const barData = [
  { letter: 'A', frequency: 816 },
  { letter: 'B', frequency: 149 },
  { letter: 'C', frequency: 278 },
  { letter: 'D', frequency: 425 },
  { letter: 'E', frequency: 1270 },
  { letter: 'F', frequency: 228 },
  { letter: 'G', frequency: 201 },
  { letter: 'H', frequency: 609 },
  { letter: 'I', frequency: 696 },
  { letter: 'J', frequency: 15 },
  { letter: 'K', frequency: 77 },
  { letter: 'L', frequency: 402 },
  { letter: 'M', frequency: 240 },
  { letter: 'N', frequency: 674 },
  { letter: 'O', frequency: 750 },
  { letter: 'P', frequency: 192 },
  { letter: 'Q', frequency: 9 },
  { letter: 'R', frequency: 598 },
];

export const mockWords = [
  {
    term: '하다',
    definition: 'to do',
  },
  {
    term: '있다',
    definition: 'to be',
  },
  {
    term: '지다',
    definition: 'to become',
  },
  {
    term: '말하다',
    definition: 'to say',
  },
  {
    term: '오다',
    definition: 'to come',
  },
  {
    term: '가다',
    definition: 'to go',
  },
  {
    term: '보다',
    definition: 'to see',
  },
  {
    term: '보내다',
    definition: 'to send',
  },
  {
    term: '가지다',
    definition: 'to have',
  },
  {
    term: '기다리다',
    definition: 'to wait',
  },
  {
    term: '만나다',
    definition: 'to meet',
  },
  {
    term: '살다',
    definition: 'to live',
  },
  {
    term: '생각하다',
    definition: 'to think',
  },
  {
    term: '주다',
    definition: 'to give',
  },
  {
    term: '받다',
    definition: 'to receive',
  },
  {
    term: '알다',
    definition: 'to know',
  },
  {
    term: '만들다',
    definition: 'to make',
  },
  {
    term: '사용하다',
    definition: 'to use',
  },
  {
    term: '배우다',
    definition: 'to learn',
  },
  {
    term: '먹다',
    definition: 'to eat',
  },
  {
    term: '마시다',
    definition: 'to drink',
  },
  {
    term: '웃다',
    definition: 'to laugh',
  },
  {
    term: '읽다',
    definition: 'to read',
  },
  {
    term: '쓰다',
    definition: 'to write',
  },
];

export const cardData = [
  {
    word: '망하다',
    frequency: 3162,
    minOrder: 6,
    minStart: 3,
    sentence: '아, 망했다, 이거',
    translation: "Oh, I'm screwed.",
    start: 3,
    length: 2,
    pos: 'Verb',
    definitions: [
      'to be ruined',
      'to be destroyed',
      'to damn you',
      'to be doomed',
    ],
    title: 'Parasite',
  },
  {
    word: '공짜',
    frequency: 7884,
    minOrder: 7,
    minStart: 0,
    sentence: '공짜 와이파이 못 쓴다, 이제',
    translation: "I can't use free Wi-Fi anymore.",
    start: 0,
    length: 2,
    pos: 'Noun',
    definitions: ['something gained free of charge', 'free'],
    title: 'Parasite',
  },
  {
    word: '와이파',
    frequency: null,
    minOrder: 7,
    minStart: 3,
    sentence: '공짜 와이파이 못 쓴다, 이제',
    translation: "I can't use free Wi-Fi anymore.",
    start: 3,
    length: 3,
    pos: 'Noun',
    definitions: ['wi-fi'],
    title: 'Parasite',
  },
  {
    word: '못',
    frequency: 24450,
    minOrder: 7,
    minStart: 8,
    sentence: '공짜 와이파이 못 쓴다, 이제',
    translation: "I can't use free Wi-Fi anymore.",
    start: 8,
    length: 1,
    pos: 'Adverb',
    definitions: ['not', 'nail'],
    title: 'Parasite',
  },
  {
    word: '쓰다',
    frequency: 35256,
    minOrder: 7,
    minStart: 10,
    sentence: '공짜 와이파이 못 쓴다, 이제',
    translation: "I can't use free Wi-Fi anymore.",
    start: 10,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to write',
      'to compose',
      'to put down',
      'to make',
      'to wear',
      'to put on',
      'to be covered with',
      'to put up',
      'to hold',
      'to raise',
      'to be falsely charged',
      'to be falsely accused',
      'to use',
      'to work with',
      'to make use of',
      'to employ',
      'to hire',
      'to engage',
      'to put',
      'to give a treat',
      'to treat someone',
      'to spend',
      'to consume',
      'to exert',
      'to exercise',
      'to be unreasonable',
      'to insist',
      'to put in motion',
      'to speak',
      'to be suitable',
      'to be all right',
    ],
    title: 'Parasite',
  },
  {
    word: '이제',
    frequency: 385,
    minOrder: 7,
    minStart: 14,
    sentence: '공짜 와이파이 못 쓴다, 이제',
    translation: "I can't use free Wi-Fi anymore.",
    start: 14,
    length: 2,
    pos: 'Adverb',
    definitions: ['now', 'henceforth', 'henceforward'],
    title: 'Parasite',
  },
  {
    word: '씁',
    frequency: null,
    minOrder: 8,
    minStart: 0,
    sentence: '씁, 야, 기정아',
    translation: 'Hey, Kijung.',
    start: 0,
    length: 1,
    pos: 'Noun',
    definitions: ['bitter'],
    title: 'Parasite',
  },
  {
    word: '윗집',
    frequency: 60376,
    minOrder: 10,
    minStart: 3,
    sentence: '야, 윗집 아줌마네 iptime암호를 거셨다, 드디어',
    translation: 'Hey, the lady upstairs has an iptime password, finally.',
    start: 3,
    length: 2,
    pos: 'Noun',
    definitions: ['upper house', 'apartment above', 'upstairs'],
    title: 'Parasite',
  },
  {
    word: '아줌마',
    frequency: 1574,
    minOrder: 10,
    minStart: 6,
    sentence: '야, 윗집 아줌마네 iptime암호를 거셨다, 드디어',
    translation: 'Hey, the lady upstairs has an iptime password, finally.',
    start: 6,
    length: 3,
    pos: 'Noun',
    definitions: ['auntie', 'aunty', 'lady', "ma'am"],
    title: 'Parasite',
  },
  {
    word: '암호',
    frequency: 7940,
    minOrder: 10,
    minStart: 17,
    sentence: '야, 윗집 아줌마네 iptime암호를 거셨다, 드디어',
    translation: 'Hey, the lady upstairs has an iptime password, finally.',
    start: 17,
    length: 2,
    pos: 'Noun',
    definitions: [
      'cryptograph',
      'secret code',
      'secret language',
      'password',
      'countersign',
      'a secret code',
    ],
    title: 'Parasite',
  },
  {
    word: '거시다',
    frequency: null,
    minOrder: 10,
    minStart: 21,
    sentence: '야, 윗집 아줌마네 iptime암호를 거셨다, 드디어',
    translation: 'Hey, the lady upstairs has an iptime password, finally.',
    start: 21,
    length: 2,
    pos: 'Verb',
    definitions: ["to it's a thing"],
    title: 'Parasite',
  },
  {
    word: '드디어',
    frequency: 2003,
    minOrder: 10,
    minStart: 26,
    sentence: '야, 윗집 아줌마네 iptime암호를 거셨다, 드디어',
    translation: 'Hey, the lady upstairs has an iptime password, finally.',
    start: 26,
    length: 3,
    pos: 'Adverb',
    definitions: ['at last', 'finally'],
    title: 'Parasite',
  },
  {
    word: '누르다',
    frequency: 1184,
    minOrder: 12,
    minStart: 8,
    sentence: '1에서 9까지 눌러 봤어?',
    translation: 'Did you press 1 to 9?',
    start: 8,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to press',
      'to push',
      'to repress',
      'to suppress',
      'to control',
      'to beat',
      'to make',
      'to stay',
    ],
    title: 'Parasite',
  },
  {
    word: '안',
    frequency: 64180,
    minOrder: 13,
    minStart: 3,
    sentence: '어, 안 돼',
    translation: 'Oh, no.',
    start: 3,
    length: 1,
    pos: 'Adverb',
    definitions: ['not', 'inside'],
    title: 'Parasite',
  },
  {
    word: '되다',
    frequency: 64828,
    minOrder: 13,
    minStart: 5,
    sentence: '어, 안 돼',
    translation: 'Oh, no.',
    start: 5,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to become',
      'to turn',
      'to come',
      'to fall',
      'to reach',
      'to amount to',
      'to be of virtue',
      'to feel',
      'to make',
      'to be made of',
      'to be made from',
      'to be made up of',
      'to be composed of',
      'to consist of',
      'to be under',
      'to be completed',
      'to be finished',
      'to work',
      'to go well',
      'to grow well',
      'to run down',
      'to get to',
      'to be supposed to',
      'to be bound to',
      'to be scheduled to',
      'to be designed to',
      'to be required to',
      'to should',
      'to have to',
      'to need to',
      'to ought to',
      'to do',
      'to be enough',
      'to not be allowed',
      'to not be permitted',
      'to be allowed',
      'to be permitted',
      'to can',
      'to may',
      'to get',
      'to constitute',
    ],
    title: 'Parasite',
  },
  {
    word: '반대',
    frequency: 7102,
    minOrder: 14,
    minStart: 0,
    sentence: '반대 순서로도 해 봐',
    translation: 'Do it in the opposite order.',
    start: 0,
    length: 2,
    pos: 'Noun',
    definitions: ['opposite', 'contrary', 'opposition', 'objection'],
    title: 'Parasite',
  },
  {
    word: '순서',
    frequency: 1867,
    minOrder: 14,
    minStart: 3,
    sentence: '반대 순서로도 해 봐',
    translation: 'Do it in the opposite order.',
    start: 3,
    length: 2,
    pos: 'Noun',
    definitions: ['order', 'sequence', 'procedure', 'process'],
    title: 'Parasite',
  },
  {
    word: '하다',
    frequency: 999999,
    minOrder: 14,
    minStart: 8,
    sentence: '반대 순서로도 해 봐',
    translation: 'Do it in the opposite order.',
    start: 8,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to do',
      'to perform',
      'to make',
      'to wear',
      'to drink',
      'to smoke',
      'to work',
      'to run',
      'to engage in',
      'to serve',
      'to play',
      'to get',
      'to become',
      'to buy',
      'to take',
      'to cost',
      'to prove',
      'to live up to',
      'to distinguish',
      'to handle',
      'to pick out',
      'to choose',
      'to put',
      'to decide',
      "to make up one's mind",
      'to call',
      'to name',
      'to result from',
      'to make a transit',
      'to reach',
      'to say',
      'to treat',
      'to think',
      'to figure',
      'to sound',
      'to go',
      'to mean',
    ],
    title: 'Parasite',
  },
  {
    word: '아이씨',
    frequency: null,
    minOrder: 16,
    minStart: 0,
    sentence: '아이씨, 뭐야, 그럼',
    translation: 'What the hell, then?',
    start: 0,
    length: 3,
    pos: 'Noun',
    definitions: ["c'mon"],
    title: 'Parasite',
  },
  {
    word: '문자',
    frequency: 31377,
    minOrder: 17,
    minStart: 3,
    sentence: '그, 문자고 카톡이고 다 안 되는 거야?',
    translation: "You can't text me or text me?",
    start: 3,
    length: 2,
    pos: 'Noun',
    definitions: ['letter', 'letters', 'text message'],
    title: 'Parasite',
  },
  {
    word: '톡',
    frequency: null,
    minOrder: 17,
    minStart: 8,
    sentence: '그, 문자고 카톡이고 다 안 되는 거야?',
    translation: "You can't text me or text me?",
    start: 8,
    length: 1,
    pos: 'Noun',
    definitions: ['tok'],
    title: 'Parasite',
  },
  {
    word: '다',
    frequency: 50327,
    minOrder: 17,
    minStart: 12,
    sentence: '그, 문자고 카톡이고 다 안 되는 거야?',
    translation: "You can't text me or text me?",
    start: 12,
    length: 1,
    pos: 'Adverb',
    definitions: [
      'all',
      'everything',
      'almost',
      'surprisingly',
      'unexpectedly',
      'completely',
    ],
    title: 'Parasite',
  },
  {
    word: '그렇다',
    frequency: 31,
    minOrder: 18,
    minStart: 0,
    sentence: '그렇지',
    translation: "That's right.",
    start: 0,
    length: 2,
    pos: 'Adjective',
    definitions: [
      'so',
      'as such',
      'like that',
      'same',
      'so so',
      'that’s right',
    ],
    title: 'Parasite',
  },
  {
    word: '씨',
    frequency: 58108,
    minOrder: 20,
    minStart: 3,
    sentence: '이, 씨발, 자는 척하지 말고',
    translation: "Don't pretend to be asleep.",
    start: 3,
    length: 1,
    pos: 'Noun',
    definitions: ['seed', 'sperm', 'lineage'],
    title: 'Parasite',
  },
  {
    word: '자다',
    frequency: 473,
    minOrder: 20,
    minStart: 7,
    sentence: '이, 씨발, 자는 척하지 말고',
    translation: "Don't pretend to be asleep.",
    start: 7,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to sleep',
      'to stop',
      'to be flattened',
      'to remain dormant',
      'to sleep with',
      'to have sex',
    ],
    title: 'Parasite',
  },
  {
    word: '어떻다',
    frequency: 76,
    minOrder: 21,
    minStart: 0,
    sentence: '어떻게 생각하셔?',
    translation: 'What do you think?',
    start: 0,
    length: 2,
    pos: 'Adjective',
    definitions: ['such', 'how is it'],
    title: 'Parasite',
  },
  {
    word: '생각',
    frequency: 55931,
    minOrder: 21,
    minStart: 4,
    sentence: '어떻게 생각하셔?',
    translation: 'What do you think?',
    start: 4,
    length: 2,
    pos: 'Noun',
    definitions: [
      'thought',
      'memory',
      'craving',
      'appetite',
      'mind',
      'decision',
      'expectation',
      'imagination',
      'opinion',
      'view',
      'feeling',
      'idea',
      'care',
      'heart',
      'thoughtfulness',
    ],
    title: 'Parasite',
  },
  {
    word: '핸드폰',
    frequency: 999999,
    minOrder: 22,
    minStart: 0,
    sentence: '핸드폰도 다 끊기고',
    translation: "I'm losing all my cell phones.",
    start: 0,
    length: 3,
    pos: 'Noun',
    definitions: ['mobile phone', 'cellular phone', 'cell phone'],
    title: 'Parasite',
  },
  {
    word: '끊기다',
    frequency: 2793,
    minOrder: 22,
    minStart: 7,
    sentence: '핸드폰도 다 끊기고',
    translation: "I'm losing all my cell phones.",
    start: 7,
    length: 2,
    pos: 'Verb',
    definitions: [
      'to snap',
      'to collapse',
      'to break',
      'to be broken off',
      'to be cut off',
      'to be stopped',
      'to be quitted',
      'to be disconnected',
      'to be cancelled',
      'to be blocked',
      'to be paused',
      'to be deserted',
      'to be killed',
      'to die',
    ],
    title: 'Parasite',
  },
  {
    word: '와이',
    frequency: null,
    minOrder: 23,
    minStart: 0,
    sentence: '와이파이도 다 끊기고, 응?',
    translation: 'The Wi-Fi is disconnected, too, huh?',
    start: 0,
    length: 2,
    pos: 'Noun',
    definitions: ['y'],
    title: 'Parasite',
  },
  {
    word: '이',
    frequency: 60959,
    minOrder: 23,
    minStart: 3,
    sentence: '와이파이도 다 끊기고, 응?',
    translation: 'The Wi-Fi is disconnected, too, huh?',
    start: 3,
    length: 1,
    pos: 'Noun',
    definitions: ['louse', 'i', 'tooth', 'teeth', 'indented part'],
    title: 'Parasite',
  },
  {
    word: '계획',
    frequency: 301,
    minOrder: 24,
    minStart: 4,
    sentence: '씨발, 계획이 뭐야, 응?',
    translation: "Damn it, what's the plan, huh?",
    start: 4,
    length: 2,
    pos: 'Noun',
    definitions: ['plan', 'program', 'scheme', 'design'],
    title: 'Parasite',
  },
  {
    word: '기',
    frequency: 64532,
    minOrder: 26,
    minStart: 3,
    sentence: '-  기우야-  예, 아버지',
    translation: '- Kiu. - Yes, Father.',
    start: 3,
    length: 1,
    pos: 'Noun',
    definitions: [
      'spirit',
      'energy',
      'enthusiasm',
      'passion',
      'introduction stage in composition',
      'course',
      'class',
      'flag',
    ],
    title: 'Parasite',
  },
  {
    word: '아버지',
    frequency: 148,
    minOrder: 26,
    minStart: 12,
    sentence: '-  기우야-  예, 아버지',
    translation: '- Kiu. - Yes, Father.',
    start: 12,
    length: 3,
    pos: 'Noun',
    definitions: [
      'father',
      'male parent',
      "someone's father",
      "father of one's child",
      'Father',
    ],
    title: 'Parasite',
  },
  {
    word: '와',
    frequency: 59750,
    minOrder: 27,
    minStart: 0,
    sentence: '와이파이 높게 들어야 돼, 높게',
    translation: 'Wi-Fi needs to be high, high.',
    start: 0,
    length: 1,
    pos: 'Noun',
    definitions: ['wa', 'wow'],
    title: 'Parasite',
  },
  {
    word: '파',
    frequency: 999999,
    minOrder: 27,
    minStart: 2,
    sentence: '와이파이 높게 들어야 돼, 높게',
    translation: 'Wi-Fi needs to be high, high.',
    start: 2,
    length: 1,
    pos: 'Noun',
    definitions: [
      'green onion',
      'scallion',
      'faction',
      'party',
      'clan',
      'fa',
      'welsh onion',
    ],
    title: 'Parasite',
  },
  {
    word: '높다',
    frequency: 212,
    minOrder: 27,
    minStart: 5,
    sentence: '와이파이 높게 들어야 돼, 높게',
    translation: 'Wi-Fi needs to be high, high.',
    start: 5,
    length: 1,
    pos: 'Adjective',
    definitions: [
      'high',
      'lofty',
      'expensive',
      'high-ranking',
      'noble',
      'exalted',
      'high-pitched',
      'well-known',
      'strong',
      'loud',
      'to be high',
    ],
    title: 'Parasite',
  },
  {
    word: '듣다',
    frequency: 34846,
    minOrder: 27,
    minStart: 8,
    sentence: '와이파이 높게 들어야 돼, 높게',
    translation: 'Wi-Fi needs to be high, high.',
    start: 8,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to fall in drops',
      'to hear',
      'to listen to',
      'to follow',
      'to obey',
      'to heed',
      'to work',
      'to learn',
      'to receive',
      'to get',
      'to regard',
      'to understand',
      'to listen',
    ],
    title: 'Parasite',
  },
  {
    word: '구석구석',
    frequency: 4549,
    minOrder: 28,
    minStart: 0,
    sentence: '구석구석, 그, 샅샅이…그, 저, 해야 돼',
    translation: 'Every nook and cranny, he...You, you, you have to.',
    start: 0,
    length: 4,
    pos: 'Noun',
    definitions: ['everywhere', 'every nook and cranny'],
    title: 'Parasite',
  },
  {
    word: '샅샅이',
    frequency: 11827,
    minOrder: 28,
    minStart: 9,
    sentence: '구석구석, 그, 샅샅이…그, 저, 해야 돼',
    translation: 'Every nook and cranny, he...You, you, you have to.',
    start: 9,
    length: 3,
    pos: 'Adverb',
    definitions: ['thoroughly', 'completely', 'through and through'],
    title: 'Parasite',
  },
  {
    word: '그',
    frequency: null,
    minOrder: 28,
    minStart: 13,
    sentence: '구석구석, 그, 샅샅이…그, 저, 해야 돼',
    translation: 'Every nook and cranny, he...You, you, you have to.',
    start: 13,
    length: 1,
    pos: 'Adverb',
    definitions: ['that'],
    title: 'Parasite',
  },
  {
    word: '꼽등',
    frequency: null,
    minOrder: 30,
    minStart: 0,
    sentence: '꼽등이, 이…',
    translation: 'Hunchback, this...',
    start: 0,
    length: 2,
    pos: 'Noun',
    definitions: ['hunchback'],
    title: 'Parasite',
  },
  {
    word: '잡히다',
    frequency: 21745,
    minOrder: 32,
    minStart: 0,
    sentence: '잡힌다',
    translation: "I'm",
    start: 0,
    length: 2,
    pos: 'Verb',
    definitions: [
      'to be created',
      'to be formed',
      'to be arrested',
      'to be held',
      'to be caught',
      'to be butchered',
      'to be taken',
      'to be grabbed',
      'to be gotten',
      'to be landed',
      'to be established',
      'to be settled',
      'to be set',
      'to be gotten right',
      'to be kept in check',
      'to be still',
      'to be quiet',
      'to be figured out',
      'to be found',
      'to be captured',
      "to be caught in one's own words",
      'to be pawned',
      'to be estimated',
      'to be made',
      'to have someone hold something',
      'to have someone butcher an animal',
      'to get caught',
    ],
    title: 'Parasite',
  },
  {
    word: '진짜',
    frequency: 999999,
    minOrder: 33,
    minStart: 0,
    sentence: '진짜? 잡혔어?',
    translation: 'Really? You got caught?',
    start: 0,
    length: 2,
    pos: 'Noun',
    definitions: ['authentic', 'the real thing'],
    title: 'Parasite',
  },
  {
    word: '커피',
    frequency: 999999,
    minOrder: 35,
    minStart: 4,
    sentence: "이거 '커피 나라 2G'",
    translation: 'This is Coffee Country 2G.',
    start: 4,
    length: 2,
    pos: 'Noun',
    definitions: ['coffee fruit', 'coffee powder', 'coffee'],
    title: 'Parasite',
  },
  {
    word: '나라',
    frequency: 233,
    minOrder: 35,
    minStart: 7,
    sentence: "이거 '커피 나라 2G'",
    translation: 'This is Coffee Country 2G.',
    start: 7,
    length: 2,
    pos: 'Noun',
    definitions: ['country', 'nation', 'state', 'world'],
    title: 'Parasite',
  },
  {
    word: '근처',
    frequency: 1547,
    minOrder: 36,
    minStart: 2,
    sentence: '이 근처에 카페 새로 생긴 건가?',
    translation: 'Is there a new cafe around here?',
    start: 2,
    length: 2,
    pos: 'Noun',
    definitions: ['vicinity', 'neighborhood', 'near'],
    title: 'Parasite',
  },
  {
    word: '카페',
    frequency: 999999,
    minOrder: 36,
    minStart: 6,
    sentence: '이 근처에 카페 새로 생긴 건가?',
    translation: 'Is there a new cafe around here?',
    start: 6,
    length: 2,
    pos: 'Noun',
    definitions: ['cafe', 'coffee shop'],
    title: 'Parasite',
  },
  {
    word: '새로',
    frequency: 994,
    minOrder: 36,
    minStart: 9,
    sentence: '이 근처에 카페 새로 생긴 건가?',
    translation: 'Is there a new cafe around here?',
    start: 9,
    length: 2,
    pos: 'Adverb',
    definitions: ['newly', 'freshly'],
    title: 'Parasite',
  },
  {
    word: '생기다',
    frequency: 18228,
    minOrder: 36,
    minStart: 12,
    sentence: '이 근처에 카페 새로 생긴 건가?',
    translation: 'Is there a new cafe around here?',
    start: 12,
    length: 2,
    pos: 'Verb',
    definitions: [
      'to be formed',
      'to come into being',
      'to obtain',
      'to get',
      'to occur',
      'to take place',
      'to look',
      'to come up',
    ],
    title: 'Parasite',
  },
  {
    word: '왜',
    frequency: 59816,
    minOrder: 37,
    minStart: 4,
    sentence: '뭐야, 왜 난 안 잡히지?',
    translation: "What, why can't I get caught?",
    start: 4,
    length: 1,
    pos: 'Adverb',
    definitions: ['why'],
    title: 'Parasite',
  },
  {
    word: '일',
    frequency: 18121,
    minOrder: 38,
    minStart: 0,
    sentence: '일로 바싹 올라와 봐',
    translation: 'Come up close to me.',
    start: 0,
    length: 1,
    pos: 'Noun',
    definitions: [
      'work',
      'labor',
      'scheme',
      'plot',
      'project',
      'matter',
      'affair',
      'act',
      'business',
      'engagement',
      'circumstances',
      'things',
      'experience',
      'case',
      'Sunday',
      'day',
    ],
    title: 'Parasite',
  },
  {
    word: '바싹',
    frequency: 63969,
    minOrder: 38,
    minStart: 3,
    sentence: '일로 바싹 올라와 봐',
    translation: 'Come up close to me.',
    start: 3,
    length: 2,
    pos: 'Adverb',
    definitions: [
      'completely',
      'closely',
      'tightly',
      'drastically',
      'stubbornly',
      'stiffly',
      'thinly',
      'right away',
      'close',
    ],
    title: 'Parasite',
  },
  {
    word: '올라오다',
    frequency: 1212,
    minOrder: 38,
    minStart: 6,
    sentence: '일로 바싹 올라와 봐',
    translation: 'Come up close to me.',
    start: 6,
    length: 3,
    pos: 'Verb',
    definitions: [
      'to come up',
      'to rise',
      'to ascend',
      'to come to the capital',
      'to come to Seoul',
      'to advance to',
      'to go ashore',
      'to go on shore',
      'to be put',
      'to be submitted',
      'to be sent',
      'to throw up',
      'to well up',
    ],
    title: 'Parasite',
  },
  {
    word: '보다',
    frequency: 684,
    minOrder: 38,
    minStart: 10,
    sentence: '일로 바싹 올라와 봐',
    translation: 'Come up close to me.',
    start: 10,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to see',
      'to look at',
      'to notice',
      'to watch',
      'to enjoy',
      'to read',
      'to take a look at',
      'to look in',
      'to meet',
      'to take care of',
      'to look after',
      'to guard',
      'to assess',
      'to judge from',
      'to have told',
      'to take',
      'to work on',
      'to work',
      'to do business',
      'to achieve',
      'to reach',
      'to get to',
      'to prepare',
      'to fix',
      'to make',
      'to relieve, do',
      'to have',
      'to suffer',
      'to experiecne',
      'to gain',
      'to examine',
      'to subscribe to',
      'to taste',
      'to sample',
      'to badmouth',
      'to speak ill of',
      'to recognize',
      'to wait for',
      'to await',
      'to look for',
      'to purchase',
      'to buy',
      'to get',
      'to take into account',
      'to consider',
      'to depend on',
      'to rely on',
      'to count on',
      'to attend',
      'to go to',
      'to think of',
      'to regard',
    ],
    title: 'Parasite',
  },
  {
    word: '그러다',
    frequency: 67,
    minOrder: 41,
    minStart: 6,
    sentence: '아, 저, 그러면은 카톡 한번 확인해 봐',
    translation: 'Oh, well, check your kakaotalk.',
    start: 6,
    length: 2,
    pos: 'Verb',
    definitions: ['to do so', 'to say so', 'to then'],
    title: 'Parasite',
  },
  {
    word: '카톡',
    frequency: null,
    minOrder: 41,
    minStart: 11,
    sentence: '아, 저, 그러면은 카톡 한번 확인해 봐',
    translation: 'Oh, well, check your kakaotalk.',
    start: 11,
    length: 2,
    pos: 'Noun',
    definitions: ['kakao talk'],
    title: 'Parasite',
  },
  {
    word: '한',
    frequency: 999999,
    minOrder: 41,
    minStart: 14,
    sentence: '아, 저, 그러면은 카톡 한번 확인해 봐',
    translation: 'Oh, well, check your kakaotalk.',
    start: 14,
    length: 1,
    pos: 'Noun',
    definitions: [
      'han',
      'limit',
      'end',
      'bound',
      'being as long as',
      'being as far as',
      'a',
    ],
    title: 'Parasite',
  },
  {
    word: '확인',
    frequency: 999999,
    minOrder: 41,
    minStart: 17,
    sentence: '아, 저, 그러면은 카톡 한번 확인해 봐',
    translation: 'Oh, well, check your kakaotalk.',
    start: 17,
    length: 2,
    pos: 'Noun',
    definitions: ['check', 'affirmation', 'confirmation', 'verification'],
    title: 'Parasite',
  },
  {
    word: '시대',
    frequency: 57471,
    minOrder: 42,
    minStart: 5,
    sentence: '저, 피자시대 연락 준다 그랬거든',
    translation: "Well, he said he'd call the Pizza Age.",
    start: 5,
    length: 2,
    pos: 'Noun',
    definitions: ['period', 'time', 'era'],
    title: 'Parasite',
  },
  {
    word: '연락',
    frequency: 2174,
    minOrder: 42,
    minStart: 8,
    sentence: '저, 피자시대 연락 준다 그랬거든',
    translation: "Well, he said he'd call the Pizza Age.",
    start: 8,
    length: 2,
    pos: 'Noun',
    definitions: ['communication', 'contact'],
    title: 'Parasite',
  },
  {
    word: '주다',
    frequency: 92,
    minOrder: 42,
    minStart: 11,
    sentence: '저, 피자시대 연락 준다 그랬거든',
    translation: "Well, he said he'd call the Pizza Age.",
    start: 11,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to give',
      'to assign',
      'to inflict',
      'to unwind further',
      'to warn',
      'to throw',
      'to inject',
      'to apply',
      'to add to',
      'to open',
    ],
    title: 'Parasite',
  },
  {
    word: '잠깐',
    frequency: 61714,
    minOrder: 43,
    minStart: 3,
    sentence: '어, 잠깐만',
    translation: 'Oh, wait.',
    start: 3,
    length: 2,
    pos: 'Noun',
    definitions: ['while', 'moment', 'the passing moment'],
    title: 'Parasite',
  },
  {
    word: '있다',
    frequency: 63661,
    minOrder: 44,
    minStart: 6,
    sentence: '어, 여기 있네, 피자시대',
    translation: 'Uh, here it is, the Pizza Age.',
    start: 6,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to be',
      'to stay',
      'to work for',
      'to serve',
      'to keep',
      'to exist',
    ],
    title: 'Parasite',
  },
  {
    word: '좀',
    frequency: 23123,
    minOrder: 47,
    minStart: 9,
    sentence: '와, 아, 이것 좀 한번 보세요들',
    translation: 'Wow, oh, look at this.Field',
    start: 9,
    length: 1,
    pos: 'Adverb',
    definitions: ['a little', 'please', 'very', 'pretty', 'some'],
    title: 'Parasite',
  },
  {
    word: '번',
    frequency: null,
    minOrder: 47,
    minStart: 12,
    sentence: '와, 아, 이것 좀 한번 보세요들',
    translation: 'Wow, oh, look at this.Field',
    start: 12,
    length: 1,
    pos: 'Noun',
    definitions: ['earned'],
    title: 'Parasite',
  },
  {
    word: '속도',
    frequency: 56751,
    minOrder: 48,
    minStart: 6,
    sentence: '우리도 이 속도로 하면',
    translation: 'If we do it at this speed,',
    start: 6,
    length: 2,
    pos: 'Noun',
    definitions: ['speed'],
    title: 'Parasite',
  },
  {
    word: '오늘',
    frequency: 438,
    minOrder: 49,
    minStart: 0,
    sentence: '오늘 중에이거 다 끝낼 수 있을 거 같은데',
    translation: "I think we'll be able to finish this all of this today.",
    start: 0,
    length: 2,
    pos: 'Noun',
    definitions: ['today'],
    title: 'Parasite',
  },
  {
    word: '에',
    frequency: 1155,
    minOrder: 49,
    minStart: 4,
    sentence: '오늘 중에이거 다 끝낼 수 있을 거 같은데',
    translation: "I think we'll be able to finish this all of this today.",
    start: 4,
    length: 1,
    pos: 'Noun',
    definitions: ['e', 'to'],
    title: 'Parasite',
  },
  {
    word: '끝내다',
    frequency: 1271,
    minOrder: 49,
    minStart: 10,
    sentence: '오늘 중에이거 다 끝낼 수 있을 거 같은데',
    translation: "I think we'll be able to finish this all of this today.",
    start: 10,
    length: 2,
    pos: 'Verb',
    definitions: ['to complete', 'to finish', 'to cut off'],
    title: 'Parasite',
  },
  {
    word: '같다',
    frequency: 18,
    minOrder: 49,
    minStart: 20,
    sentence: '오늘 중에이거 다 끝낼 수 있을 거 같은데',
    translation: "I think we'll be able to finish this all of this today.",
    start: 20,
    length: 1,
    pos: 'Adjective',
    definitions: [
      'same',
      'identical',
      'equal',
      'similar',
      'like',
      'such as',
      'if',
      'in case',
      'just like',
    ],
    title: 'Parasite',
  },
  {
    word: '돈',
    frequency: 28995,
    minOrder: 50,
    minStart: 3,
    sentence: '오늘 돈 다 받는 거죠?',
    translation: "You're getting all the money today, right?",
    start: 3,
    length: 1,
    pos: 'Noun',
    definitions: ['money', 'cost', 'expense', 'riches'],
    title: 'Parasite',
  },
  {
    word: '받다',
    frequency: 19936,
    minOrder: 50,
    minStart: 7,
    sentence: '오늘 돈 다 받는 거죠?',
    translation: "You're getting all the money today, right?",
    start: 7,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to receive',
      'to get',
      'to collect',
      'to be affected by',
      'to be influenced by',
      'to obtain',
      'to buy',
      'to purchase',
      'to source',
      'to catch',
      'to be exposed to',
      'to be generous',
      'to pamper',
      'to be shot',
      'to be gunned',
      'to be hit',
      'to add',
      'to take over',
      'to deliver',
      'to fill',
      'to go well with',
      'to look good',
      'to be agreeable',
      'to stay',
      'to look better',
      'to butt',
      'to gore',
      'to resist',
      'to confront',
    ],
    title: 'Parasite',
  },
  {
    word: '서다',
    frequency: 204,
    minOrder: 51,
    minStart: 3,
    sentence: '이, 서서 하는구나, 이게',
    translation: "Oh, you're standing up.",
    start: 3,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to stand',
      'to be made',
      'to be sharpened',
      'to become sharp',
      'to be established',
      'to be restored',
      'to be conceived',
      'to be formed',
      'to be created',
      'to stop',
      'to come to a halt',
      'to become erect',
      'to go up',
      'to be built',
      'to be erected',
      'to be inaugurated',
      'to pull over',
      'to be on a side',
      'to take a side',
      'to be open',
      'to start',
      'to appear',
      'to be saved',
      'to be maintained',
      'to assume',
      'to queue',
      'to stand in line',
    ],
    title: 'Parasite',
  },
  {
    word: '달',
    frequency: 50534,
    minOrder: 52,
    minStart: 7,
    sentence: '아유, 얘는 달인이구먼, 뭘',
    translation: "Oh, he's a master.",
    start: 7,
    length: 1,
    pos: 'Noun',
    definitions: ['moon', 'month'],
    title: 'Parasite',
  },
  {
    word: '요즘',
    frequency: 470,
    minOrder: 55,
    minStart: 6,
    sentence: '-  어, 요즘도 저런 걸 하네-  그러게요',
    translation: "- Uh, that's what they do these days. - Yeah.",
    start: 6,
    length: 2,
    pos: 'Noun',
    definitions: ['nowadays', 'these days'],
    title: 'Parasite',
  },
  {
    word: '창문',
    frequency: 999999,
    minOrder: 56,
    minStart: 0,
    sentence: '창문 닫아',
    translation: 'Close the window.',
    start: 0,
    length: 2,
    pos: 'Noun',
    definitions: ['window'],
    title: 'Parasite',
  },
  {
    word: '닫다',
    frequency: 26102,
    minOrder: 56,
    minStart: 3,
    sentence: '창문 닫아',
    translation: 'Close the window.',
    start: 3,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to shut',
      'to close the door',
      "to close one's business",
      'to go out of business',
      'to close',
    ],
    title: 'Parasite',
  },
  {
    word: '놓다',
    frequency: 29532,
    minOrder: 57,
    minStart: 0,
    sentence: '놔둬 봐, 공짜로 집 안에 소독도 하고',
    translation: 'Just leave, disinfection and in the house for free.',
    start: 0,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to let go',
      'to let loose',
      'to stop',
      'to relax',
      'to ease',
      'to bet',
      'to about',
      'to on',
      'to calculate',
      'to reckon',
      'to increase',
      'to speed up',
      'to recover from',
      'to put',
      'to place',
      'to construct',
      'to lay',
      'to set',
      'to adorn',
      'to embroider',
      'to engrave',
      'to stuff',
      'to add',
      'to sow',
      'to put in',
      'to inject',
      'to needle',
      'to give',
      'to make',
      'to loan',
      'to bid',
      'to name',
      'to shoot',
      'to send',
      'to use friendly terms',
    ],
    title: 'Parasite',
  },
  {
    word: '집',
    frequency: 999999,
    minOrder: 57,
    minStart: 10,
    sentence: '놔둬 봐, 공짜로 집 안에 소독도 하고',
    translation: 'Just leave, disinfection and in the house for free.',
    start: 10,
    length: 1,
    pos: 'Noun',
    definitions: [
      'house',
      'family',
      'case',
      'holster',
      'sheath',
      'controlled point',
      'surrounded point',
      'store',
      'shop',
    ],
    title: 'Parasite',
  },
  {
    word: '소독',
    frequency: 13768,
    minOrder: 57,
    minStart: 15,
    sentence: '놔둬 봐, 공짜로 집 안에 소독도 하고',
    translation: 'Just leave, disinfection and in the house for free.',
    start: 15,
    length: 2,
    pos: 'Noun',
    definitions: ['disinfection', 'sterilization'],
    title: 'Parasite',
  },
  {
    word: '꼽등이',
    frequency: null,
    minOrder: 58,
    minStart: 0,
    sentence: '꼽등이도 없애고',
    translation: "I'll get rid of the backpickles.",
    start: 0,
    length: 3,
    pos: 'Noun',
    definitions: ['the back of a pin'],
    title: 'Parasite',
  },
  {
    word: '없애다',
    frequency: 1512,
    minOrder: 58,
    minStart: 5,
    sentence: '꼽등이도 없애고',
    translation: "I'll get rid of the backpickles.",
    start: 5,
    length: 2,
    pos: 'Verb',
    definitions: [
      'to eliminate',
      'to get rid of',
      'to eradicate',
      'to remove',
      'to take away',
      'to deprive',
      'to kill',
    ],
    title: 'Parasite',
  },
  {
    word: '그다',
    frequency: null,
    minOrder: 59,
    minStart: 0,
    sentence: '그래그래, 요새 꼽등이 너무 많아',
    translation: "Yeah, yeah, there's too many of them these days.",
    start: 0,
    length: 1,
    pos: 'Verb',
    definitions: ["to that's"],
    title: 'Parasite',
  },
  {
    word: '요새',
    frequency: 64273,
    minOrder: 59,
    minStart: 6,
    sentence: '그래그래, 요새 꼽등이 너무 많아',
    translation: "Yeah, yeah, there's too many of them these days.",
    start: 6,
    length: 2,
    pos: 'Noun',
    definitions: ['these days', 'nowadays', 'lately', 'fortress'],
    title: 'Parasite',
  },
  {
    word: '너무',
    frequency: 214,
    minOrder: 59,
    minStart: 13,
    sentence: '그래그래, 요새 꼽등이 너무 많아',
    translation: "Yeah, yeah, there's too many of them these days.",
    start: 13,
    length: 2,
    pos: 'Adverb',
    definitions: ['too'],
    title: 'Parasite',
  },
  {
    word: '많다',
    frequency: 39,
    minOrder: 59,
    minStart: 16,
    sentence: '그래그래, 요새 꼽등이 너무 많아',
    translation: "Yeah, yeah, there's too many of them these days.",
    start: 16,
    length: 1,
    pos: 'Adjective',
    definitions: ['plentiful', 'many', 'a lot of', 'to be a lot'],
    title: 'Parasite',
  },
  {
    word: '냄새',
    frequency: 892,
    minOrder: 60,
    minStart: 4,
    sentence: '아유, 냄새',
    translation: 'Oh, smell.',
    start: 4,
    length: 2,
    pos: 'Noun',
    definitions: ['smell', 'scent', 'odor', 'mood'],
    title: 'Parasite',
  },
  {
    word: '아까',
    frequency: 3020,
    minOrder: 62,
    minStart: 11,
    sentence: '아유, 아유, 내가 아까 닫으라 그랬지?',
    translation: "Oh, oh, oh, I told you to close it earlier, didn't I?",
    start: 11,
    length: 2,
    pos: 'Adverb',
    definitions: ['a little while ago', 'a moment ago', 'right before'],
    title: 'Parasite',
  },
  {
    word: '구체',
    frequency: null,
    minOrder: 68,
    minStart: 0,
    sentence: '구체적으로 뭐가 문제예요?',
    translation: "What's wrong with you specifically?",
    start: 0,
    length: 2,
    pos: 'Noun',
    definitions: ['spherical sphere'],
    title: 'Parasite',
  },
  {
    word: '문제',
    frequency: 52796,
    minOrder: 68,
    minStart: 9,
    sentence: '구체적으로 뭐가 문제예요?',
    translation: "What's wrong with you specifically?",
    start: 9,
    length: 2,
    pos: 'Noun',
    definitions: ['problem', 'question', 'issue', 'trouble'],
    title: 'Parasite',
  },
  {
    word: '예',
    frequency: 59472,
    minOrder: 69,
    minStart: 4,
    sentence: '아니, 예를 들면 여기 한번 봐요, 어?',
    translation: 'No, for example, look here, huh?',
    start: 4,
    length: 1,
    pos: 'Noun',
    definitions: [
      'old times',
      'ye',
      'example',
      'politeness',
      'courtesy',
      'ceremony',
      'etiquette',
      'decorum',
      'yes',
    ],
    title: 'Parasite',
  },
  {
    word: '들다',
    frequency: 26137,
    minOrder: 69,
    minStart: 7,
    sentence: '아니, 예를 들면 여기 한번 봐요, 어?',
    translation: 'No, for example, look here, huh?',
    start: 7,
    length: 1,
    pos: 'Verb',
    definitions: [
      'to cut well',
      'to be sharp',
      'to come in',
      'to get in',
      'to enter',
      'to move to',
      'to stay',
      'to get on',
      'to take',
      'to get into',
      'to be spent',
      'to be used',
      'to be poured',
      'to be invested',
      'to permeate',
      'to saturate with',
      'to reach',
      'to be in',
      'to be contained',
      'to fill',
      'to land in',
      'to be put under',
      'to enter into',
      'to be drawn to',
      'to be attracted to',
      'to have',
      'to be hit',
      'to be struck',
      'to start',
      'to fall',
      'to join',
      'to open',
      'to take out',
      'to come',
      'to become',
      'to grow',
      'to get',
      'to ripen',
      'to mature',
      'to catch',
      'to develop',
      'to recover',
      'to regain',
      'to strike',
      'to occur to',
      'to bear',
      'to be possessed by',
      'to do',
      'to arrange',
      'to marry',
      'to live in',
      'to hold',
      'to carry',
      'to raise',
      'to lift',
      'to give',
      'to eat',
    ],
    title: 'Parasite',
  },
  {
    word: '라인',
    frequency: 5643,
    minOrder: 70,
    minStart: 0,
    sentence: '라인이 아주 더럽게 접혔죠?',
    translation: 'The line is very dirty, right?',
    start: 0,
    length: 2,
    pos: 'Noun',
    definitions: ['line', 'outline'],
    title: 'Parasite',
  },
  {
    word: '아주',
    frequency: 28124,
    minOrder: 70,
    minStart: 4,
    sentence: '라인이 아주 더럽게 접혔죠?',
    translation: 'The line is very dirty, right?',
    start: 4,
    length: 2,
    pos: 'Adverb',
    definitions: ['very', 'so', 'extremely', 'entirely', 'utterly'],
    title: 'Parasite',
  },
  {
    word: '더럽다',
    frequency: 44448,
    minOrder: 70,
    minStart: 7,
    sentence: '라인이 아주 더럽게 접혔죠?',
    translation: 'The line is very dirty, right?',
    start: 7,
    length: 2,
    pos: 'Adjective',
    definitions: [
      'dirty',
      'nasty',
      'foul',
      'mean',
      'indecent',
      'fouled-up',
      'extreme',
    ],
    title: 'Parasite',
  },
  {
    word: '접히다',
    frequency: 10029,
    minOrder: 70,
    minStart: 11,
    sentence: '라인이 아주 더럽게 접혔죠?',
    translation: 'The line is very dirty, right?',
    start: 11,
    length: 2,
    pos: 'Verb',
    definitions: ['to be folded', 'to fold up'],
    title: 'Parasite',
  },
  {
    word: '튀어나오다',
    frequency: 999999,
    minOrder: 72,
    minStart: 5,
    sentence: '이거 왜 튀어나와요?',
    translation: 'Why is this sticking out?',
    start: 5,
    length: 4,
    pos: 'Verb',
    definitions: ['to protrude', 'to spit', 'to speak abruptly', 'to pop out'],
    title: 'Parasite',
  },
  {
    word: '접다',
    frequency: 2936,
    minOrder: 73,
    minStart: 3,
    sentence: '그럼 접다 만 거잖아요, 지금',
    translation: "That's why you stopped.",
    start: 3,
    length: 1,
    pos: 'Verb',
    definitions: ['to fold', 'to relinquish', 'to give a handicap'],
    title: 'Parasite',
  },
  {
    word: '지금',
    frequency: 63528,
    minOrder: 73,
    minStart: 14,
    sentence: '그럼 접다 만 거잖아요, 지금',
    translation: "That's why you stopped.",
    start: 14,
    length: 2,
    pos: 'Adverb',
    definitions: ['now', 'immediately', 'at this moment'],
    title: 'Parasite',
  },
];
