export const binData = [
  {
    bin: 0,
    bins: [
      { bin: 0, count: 48 },
      { bin: 1, count: 29 },
      { bin: 2, count: 74 },
      { bin: 3, count: 86 },
      { bin: 4, count: 35 },
      { bin: 5, count: 96 },
      { bin: 6, count: 55 },
    ],
  },
  {
    bin: 1,
    bins: [
      { bin: 0, count: 0 },
      { bin: 1, count: 33 },
      { bin: 2, count: 97 },
      { bin: 3, count: 24 },
      { bin: 4, count: 42 },
      { bin: 5, count: 55 },
      { bin: 6, count: 55 },
    ],
  },
  {
    bin: 2,
    bins: [
      { bin: 0, count: 53 },
      { bin: 1, count: 79 },
      { bin: 2, count: 18 },
      { bin: 3, count: 11 },
      { bin: 4, count: 16 },
      { bin: 5, count: 57 },
      { bin: 6, count: 4 },
    ],
  },
  {
    bin: 3,
    bins: [
      { bin: 0, count: 42 },
      { bin: 1, count: 28 },
      { bin: 2, count: 63 },
      { bin: 3, count: 90 },
      { bin: 4, count: 39 },
      { bin: 5, count: 21 },
      { bin: 6, count: 74 },
    ],
  },
  {
    bin: 4,
    bins: [
      { bin: 0, count: 1 },
      { bin: 1, count: 96 },
      { bin: 2, count: 22 },
      { bin: 3, count: 5 },
      { bin: 4, count: 83 },
      { bin: 5, count: 88 },
      { bin: 6, count: 29 },
    ],
  },
  {
    bin: 5,
    bins: [
      { bin: 0, count: 86 },
      { bin: 1, count: 87 },
      { bin: 2, count: 44 },
      { bin: 3, count: 14 },
      { bin: 4, count: 44 },
      { bin: 5, count: 5 },
      { bin: 6, count: 25 },
    ],
  },
  {
    bin: 6,
    bins: [
      { bin: 0, count: 76 },
      { bin: 1, count: 74 },
      { bin: 2, count: 19 },
      { bin: 3, count: 81 },
      { bin: 4, count: 44 },
      { bin: 5, count: 13 },
      { bin: 6, count: 39 },
    ],
  },
  {
    bin: 7,
    bins: [
      { bin: 0, count: 48 },
      { bin: 1, count: 99 },
      { bin: 2, count: 53 },
      { bin: 3, count: 41 },
      { bin: 4, count: 89 },
      { bin: 5, count: 56 },
      { bin: 6, count: 67 },
    ],
  },
  {
    bin: 8,
    bins: [
      { bin: 0, count: 36 },
      { bin: 1, count: 16 },
      { bin: 2, count: 30 },
      { bin: 3, count: 22 },
      { bin: 4, count: 33 },
      { bin: 5, count: 25 },
      { bin: 6, count: 79 },
    ],
  },
  {
    bin: 9,
    bins: [
      { bin: 0, count: 8 },
      { bin: 1, count: 76 },
      { bin: 2, count: 40 },
      { bin: 3, count: 7 },
      { bin: 4, count: 16 },
      { bin: 5, count: 51 },
      { bin: 6, count: 58 },
    ],
  },
  {
    bin: 10,
    bins: [
      { bin: 0, count: 38 },
      { bin: 1, count: 22 },
      { bin: 2, count: 24 },
      { bin: 3, count: 19 },
      { bin: 4, count: 34 },
      { bin: 5, count: 76 },
      { bin: 6, count: 35 },
    ],
  },
  {
    bin: 11,
    bins: [
      { bin: 0, count: 63 },
      { bin: 1, count: 94 },
      { bin: 2, count: 15 },
      { bin: 3, count: 56 },
      { bin: 4, count: 40 },
      { bin: 5, count: 57 },
      { bin: 6, count: 12 },
    ],
  },
  {
    bin: 12,
    bins: [
      { bin: 0, count: 10 },
      { bin: 1, count: 77 },
      { bin: 2, count: 16 },
      { bin: 3, count: 66 },
      { bin: 4, count: 76 },
      { bin: 5, count: 36 },
      { bin: 6, count: 82 },
    ],
  },
  {
    bin: 13,
    bins: [
      { bin: 0, count: 81 },
      { bin: 1, count: 62 },
      { bin: 2, count: 3 },
      { bin: 3, count: 88 },
      { bin: 4, count: 78 },
      { bin: 5, count: 1 },
      { bin: 6, count: 96 },
    ],
  },
  {
    bin: 14,
    bins: [
      { bin: 0, count: 14 },
      { bin: 1, count: 66 },
      { bin: 2, count: 97 },
      { bin: 3, count: 78 },
      { bin: 4, count: 45 },
      { bin: 5, count: 36 },
      { bin: 6, count: 45 },
    ],
  },
  {
    bin: 15,
    bins: [
      { bin: 0, count: 29 },
      { bin: 1, count: 38 },
      { bin: 2, count: 69 },
      { bin: 3, count: 83 },
      { bin: 4, count: 90 },
      { bin: 5, count: 33 },
      { bin: 6, count: 75 },
    ],
  },
  {
    bin: 16,
    bins: [
      { bin: 0, count: 67 },
      { bin: 1, count: 92 },
      { bin: 2, count: 26 },
      { bin: 3, count: 97 },
      { bin: 4, count: 65 },
      { bin: 5, count: 54 },
      { bin: 6, count: 15 },
    ],
  },
  {
    bin: 17,
    bins: [
      { bin: 0, count: 50 },
      { bin: 1, count: 12 },
      { bin: 2, count: 69 },
      { bin: 3, count: 72 },
      { bin: 4, count: 71 },
      { bin: 5, count: 76 },
      { bin: 6, count: 52 },
    ],
  },
  {
    bin: 18,
    bins: [
      { bin: 0, count: 96 },
      { bin: 1, count: 17 },
      { bin: 2, count: 29 },
      { bin: 3, count: 4 },
      { bin: 4, count: 65 },
      { bin: 5, count: 25 },
      { bin: 6, count: 15 },
    ],
  },
  {
    bin: 19,
    bins: [
      { bin: 0, count: 13 },
      { bin: 1, count: 82 },
      { bin: 2, count: 16 },
      { bin: 3, count: 67 },
      { bin: 4, count: 97 },
      { bin: 5, count: 87 },
      { bin: 6, count: 23 },
    ],
  },
  {
    bin: 20,
    bins: [
      { bin: 0, count: 13 },
      { bin: 1, count: 65 },
      { bin: 2, count: 76 },
      { bin: 3, count: 60 },
      { bin: 4, count: 62 },
      { bin: 5, count: 50 },
      { bin: 6, count: 50 },
    ],
  },
  {
    bin: 21,
    bins: [
      { bin: 0, count: 75 },
      { bin: 1, count: 82 },
      { bin: 2, count: 35 },
      { bin: 3, count: 95 },
      { bin: 4, count: 37 },
      { bin: 5, count: 92 },
      { bin: 6, count: 76 },
    ],
  },
  {
    bin: 22,
    bins: [
      { bin: 0, count: 53 },
      { bin: 1, count: 66 },
      { bin: 2, count: 37 },
      { bin: 3, count: 5 },
      { bin: 4, count: 32 },
      { bin: 5, count: 7 },
      { bin: 6, count: 23 },
    ],
  },
  {
    bin: 23,
    bins: [
      { bin: 0, count: 54 },
      { bin: 1, count: 83 },
      { bin: 2, count: 85 },
      { bin: 3, count: 13 },
      { bin: 4, count: 30 },
      { bin: 5, count: 32 },
      { bin: 6, count: 18 },
    ],
  },
  {
    bin: 24,
    bins: [
      { bin: 0, count: 37 },
      { bin: 1, count: 52 },
      { bin: 2, count: 37 },
      { bin: 3, count: 62 },
      { bin: 4, count: 47 },
      { bin: 5, count: 6 },
      { bin: 6, count: 17 },
    ],
  },
  {
    bin: 25,
    bins: [
      { bin: 0, count: 16 },
      { bin: 1, count: 30 },
      { bin: 2, count: 97 },
      { bin: 3, count: 80 },
      { bin: 4, count: 12 },
      { bin: 5, count: 54 },
      { bin: 6, count: 95 },
    ],
  },
  {
    bin: 26,
    bins: [
      { bin: 0, count: 29 },
      { bin: 1, count: 71 },
      { bin: 2, count: 7 },
      { bin: 3, count: 6 },
      { bin: 4, count: 34 },
      { bin: 5, count: 90 },
      { bin: 6, count: 77 },
    ],
  },
  {
    bin: 27,
    bins: [
      { bin: 0, count: 13 },
      { bin: 1, count: 9 },
      { bin: 2, count: 4 },
      { bin: 3, count: 45 },
      { bin: 4, count: 74 },
      { bin: 5, count: 99 },
      { bin: 6, count: 39 },
    ],
  },
  {
    bin: 28,
    bins: [
      { bin: 0, count: 23 },
      { bin: 1, count: 66 },
      { bin: 2, count: 10 },
      { bin: 3, count: 23 },
      { bin: 4, count: 43 },
      { bin: 5, count: 13 },
      { bin: 6, count: 1 },
    ],
  },
  {
    bin: 29,
    bins: [
      { bin: 0, count: 60 },
      { bin: 1, count: 77 },
      { bin: 2, count: 44 },
      { bin: 3, count: 37 },
      { bin: 4, count: 60 },
      { bin: 5, count: 54 },
      { bin: 6, count: 54 },
    ],
  },
  {
    bin: 30,
    bins: [
      { bin: 0, count: 76 },
      { bin: 1, count: 78 },
      { bin: 2, count: 98 },
      { bin: 3, count: 77 },
      { bin: 4, count: 21 },
      { bin: 5, count: 22 },
      { bin: 6, count: 98 },
    ],
  },
  {
    bin: 31,
    bins: [
      { bin: 0, count: 98 },
      { bin: 1, count: 84 },
      { bin: 2, count: 17 },
      { bin: 3, count: 96 },
      { bin: 4, count: 40 },
      { bin: 5, count: 21 },
      { bin: 6, count: 43 },
    ],
  },
  {
    bin: 32,
    bins: [
      { bin: 0, count: 50 },
      { bin: 1, count: 31 },
      { bin: 2, count: 52 },
      { bin: 3, count: 82 },
      { bin: 4, count: 94 },
      { bin: 5, count: 18 },
      { bin: 6, count: 62 },
    ],
  },
  {
    bin: 33,
    bins: [
      { bin: 0, count: 42 },
      { bin: 1, count: 22 },
      { bin: 2, count: 89 },
      { bin: 3, count: 52 },
      { bin: 4, count: 45 },
      { bin: 5, count: 63 },
      { bin: 6, count: 26 },
    ],
  },
  {
    bin: 34,
    bins: [
      { bin: 0, count: 97 },
      { bin: 1, count: 92 },
      { bin: 2, count: 13 },
      { bin: 3, count: 83 },
      { bin: 4, count: 6 },
      { bin: 5, count: 44 },
      { bin: 6, count: 48 },
    ],
  },
  {
    bin: 35,
    bins: [
      { bin: 0, count: 87 },
      { bin: 1, count: 12 },
      { bin: 2, count: 89 },
      { bin: 3, count: 46 },
      { bin: 4, count: 78 },
      { bin: 5, count: 28 },
      { bin: 6, count: 76 },
    ],
  },
  {
    bin: 36,
    bins: [
      { bin: 0, count: 67 },
      { bin: 1, count: 63 },
      { bin: 2, count: 49 },
      { bin: 3, count: 33 },
      { bin: 4, count: 89 },
      { bin: 5, count: 30 },
      { bin: 6, count: 88 },
    ],
  },
  {
    bin: 37,
    bins: [
      { bin: 0, count: 10 },
      { bin: 1, count: 97 },
      { bin: 2, count: 49 },
      { bin: 3, count: 68 },
      { bin: 4, count: 9 },
      { bin: 5, count: 55 },
      { bin: 6, count: 76 },
    ],
  },
  {
    bin: 38,
    bins: [
      { bin: 0, count: 19 },
      { bin: 1, count: 94 },
      { bin: 2, count: 38 },
      { bin: 3, count: 10 },
      { bin: 4, count: 41 },
      { bin: 5, count: 83 },
      { bin: 6, count: 79 },
    ],
  },
  {
    bin: 39,
    bins: [
      { bin: 0, count: 85 },
      { bin: 1, count: 45 },
      { bin: 2, count: 80 },
      { bin: 3, count: 61 },
      { bin: 4, count: 92 },
      { bin: 5, count: 72 },
      { bin: 6, count: 95 },
    ],
  },
  {
    bin: 40,
    bins: [
      { bin: 0, count: 80 },
      { bin: 1, count: 64 },
      { bin: 2, count: 49 },
      { bin: 3, count: 45 },
      { bin: 4, count: 31 },
      { bin: 5, count: 74 },
      { bin: 6, count: 51 },
    ],
  },
  {
    bin: 41,
    bins: [
      { bin: 0, count: 61 },
      { bin: 1, count: 9 },
      { bin: 2, count: 16 },
      { bin: 3, count: 60 },
      { bin: 4, count: 20 },
      { bin: 5, count: 23 },
      { bin: 6, count: 84 },
    ],
  },
  {
    bin: 42,
    bins: [
      { bin: 0, count: 42 },
      { bin: 1, count: 87 },
      { bin: 2, count: 69 },
      { bin: 3, count: 59 },
      { bin: 4, count: 89 },
      { bin: 5, count: 37 },
      { bin: 6, count: 4 },
    ],
  },
  {
    bin: 43,
    bins: [
      { bin: 0, count: 71 },
      { bin: 1, count: 97 },
      { bin: 2, count: 85 },
      { bin: 3, count: 21 },
      { bin: 4, count: 99 },
      { bin: 5, count: 77 },
      { bin: 6, count: 62 },
    ],
  },
  {
    bin: 44,
    bins: [
      { bin: 0, count: 12 },
      { bin: 1, count: 28 },
      { bin: 2, count: 6 },
      { bin: 3, count: 89 },
      { bin: 4, count: 74 },
      { bin: 5, count: 62 },
      { bin: 6, count: 89 },
    ],
  },
  {
    bin: 45,
    bins: [
      { bin: 0, count: 53 },
      { bin: 1, count: 2 },
      { bin: 2, count: 79 },
      { bin: 3, count: 73 },
      { bin: 4, count: 90 },
      { bin: 5, count: 50 },
      { bin: 6, count: 75 },
    ],
  },
  {
    bin: 46,
    bins: [
      { bin: 0, count: 32 },
      { bin: 1, count: 14 },
      { bin: 2, count: 83 },
      { bin: 3, count: 16 },
      { bin: 4, count: 30 },
      { bin: 5, count: 65 },
      { bin: 6, count: 34 },
    ],
  },
  {
    bin: 47,
    bins: [
      { bin: 0, count: 15 },
      { bin: 1, count: 8 },
      { bin: 2, count: 54 },
      { bin: 3, count: 34 },
      { bin: 4, count: 96 },
      { bin: 5, count: 76 },
      { bin: 6, count: 23 },
    ],
  },
  {
    bin: 48,
    bins: [
      { bin: 0, count: 5 },
      { bin: 1, count: 5 },
      { bin: 2, count: 91 },
      { bin: 3, count: 64 },
      { bin: 4, count: 99 },
      { bin: 5, count: 91 },
      { bin: 6, count: 51 },
    ],
  },
  {
    bin: 49,
    bins: [
      { bin: 0, count: 50 },
      { bin: 1, count: 49 },
      { bin: 2, count: 64 },
      { bin: 3, count: 46 },
      { bin: 4, count: 84 },
      { bin: 5, count: 61 },
      { bin: 6, count: 96 },
    ],
  },
  {
    bin: 50,
    bins: [
      { bin: 0, count: 40 },
      { bin: 1, count: 60 },
      { bin: 2, count: 50 },
      { bin: 3, count: 28 },
      { bin: 4, count: 73 },
      { bin: 5, count: 90 },
      { bin: 6, count: 9 },
    ],
  },
  {
    bin: 51,
    bins: [
      { bin: 0, count: 98 },
      { bin: 1, count: 9 },
      { bin: 2, count: 57 },
      { bin: 3, count: 67 },
      { bin: 4, count: 8 },
      { bin: 5, count: 78 },
      { bin: 6, count: 79 },
    ],
  },
  {
    bin: 52,
    bins: [
      { bin: 0, count: 71 },
      { bin: 1, count: 87 },
      { bin: 2, count: 69 },
      { bin: 3, count: 2 },
      { bin: 4, count: 89 },
      { bin: 5, count: 18 },
      { bin: 6, count: 86 },
    ],
  },
];

export const barData = [
  { letter: 'A', frequency: 816 },
  { letter: 'B', frequency: 149 },
  { letter: 'C', frequency: 278 },
  { letter: 'D', frequency: 425 },
  { letter: 'E', frequency: 1270 },
  { letter: 'F', frequency: 228 },
  { letter: 'G', frequency: 201 },
  { letter: 'H', frequency: 609 },
  { letter: 'I', frequency: 696 },
  { letter: 'J', frequency: 15 },
  { letter: 'K', frequency: 77 },
  { letter: 'L', frequency: 402 },
  { letter: 'M', frequency: 240 },
  { letter: 'N', frequency: 674 },
  { letter: 'O', frequency: 750 },
  { letter: 'P', frequency: 192 },
  { letter: 'Q', frequency: 9 },
  { letter: 'R', frequency: 598 },
];

export const mockReviews = [
  {
    sentenceId: null,
    sentence: '이, 씨발, 자는 척하지 말고',
    translation: "Don't pretend to be asleep.",
    term: '자다',
    start: 7,
    end: 8,
    definitions: ['sleep'],
    alt: ['stop', 'be flattened', 'have sex'],
    title: 'Parasite',
  },
  {
    sentenceId: null,
    sentence: '핸드폰도 다 끊기고',
    translation: 'My phone is disconnected.',
    term: '핸드폰',
    start: 0,
    end: 3,
    definitions: ['mobile phone', 'cellular phone'],
    alt: [],
    title: 'Parasite',
  },
  {
    sentenceId: null,
    sentence: '오늘 중에이거 다 끝낼 수 있을 거 같은데',
    translation: 'I think I can finish all of this today.',
    term: '끝내다',
    start: 10,
    end: 11,
    definitions: ['complete', 'finish'],
    alt: ['cut off'],
    title: 'Parasite',
  },
  {
    sentenceId: null,
    sentence: '아니, 그런 디테일은또 어떻게 다 알아요?',
    translation: 'How do you know all those details?',
    term: '알다',
    start: 19,
    end: 20,
    definitions: ['know', 'understand'],
    alt: ['realize', 'care about'],
    title: 'Parasite',
  },
  {
    sentenceId: null,
    sentence: '이 동네에서 평판이 되게 안 좋은데',
    translation: "I don't have a good reputation in this neighborhood.",
    term: '동네',
    start: 3,
    end: 4,
    definitions: ['neighbourhood', 'village'],
    alt: [],
    title: 'Parasite',
  },
];

export const mockWords = [
  {
    term: '하다',
    definition: 'to do',
  },
  {
    term: '있다',
    definition: 'to be',
  },
  {
    term: '지다',
    definition: 'to become',
  },
  {
    term: '말하다',
    definition: 'to say',
  },
  {
    term: '오다',
    definition: 'to come',
  },
  {
    term: '가다',
    definition: 'to go',
  },
  {
    term: '보다',
    definition: 'to see',
  },
  {
    term: '보내다',
    definition: 'to send',
  },
  {
    term: '가지다',
    definition: 'to have',
  },
  {
    term: '기다리다',
    definition: 'to wait',
  },
  {
    term: '만나다',
    definition: 'to meet',
  },
  {
    term: '살다',
    definition: 'to live',
  },
  {
    term: '생각하다',
    definition: 'to think',
  },
  {
    term: '주다',
    definition: 'to give',
  },
  {
    term: '받다',
    definition: 'to receive',
  },
  {
    term: '알다',
    definition: 'to know',
  },
  {
    term: '만들다',
    definition: 'to make',
  },
  {
    term: '사용하다',
    definition: 'to use',
  },
  {
    term: '배우다',
    definition: 'to learn',
  },
  {
    term: '먹다',
    definition: 'to eat',
  },
  {
    term: '마시다',
    definition: 'to drink',
  },
  {
    term: '웃다',
    definition: 'to laugh',
  },
  {
    term: '읽다',
    definition: 'to read',
  },
  {
    term: '쓰다',
    definition: 'to write',
  },
];
